# BCS Data Analysis Project

To frame our analysis, we must start with a concrete question to ground ourselves.
In this case, we're asking ourselves; So what's up with counter heals?
* how many do decks play on average?
* how do high performing decks relate to this average?
* how about low performing decks?

In order to answer this we'll need to:
* obtain HTML page for each decklog
* add each deck's info. into a data base (each card name and it's quantity)
* determine the names we want to know about
* query and graph the data

# Step 1 + 2
After a bit of wrangling, I've reworked these steps to start by scraping information about each event of the announcement page, so we can have information about the date of each event, and a second bit of scraping to get the link extension for each of those events off the event report page. 

Bushiroad might be weird with how their links are patterened or changed, as well as not maintaining event order between site pages, so it is wise to manually inspect the results of the scraping before feeding the results into our pipeline for data collection.

For more information about the scraping, and the schema of the table below, check out the Data Collection and Data Wrangling sections

In [2]:
# Imports not present here should remain in place during development

from os import path
import sys

import pandas as pd
from pymongo import MongoClient

In [ ]:
# BCS 25/26 Event locations
# These must manually be extracted from the bushiroad site, 
# https://en.cf-vanguard.com/event/bcs2526/
BASE_URL = "https://en.cf-vanguard.com/event/bcs2526/"

final_event_list=[
    ## ['illinois, 'Rosemont', 'NA', 'October 4, 2025'],
    ## ['mexico', 'Mexico', 'NA', 'November 8, 2025'],
    ## ['bcs2526-houston-tx', 'TX', 'NA', 'November 22, 2025'],
    ## ['bcs2526-california', 'LA', 'NA', 'December 6, 2025'],
    ## ['vancouver', 'BC', 'NA', 'January 10, 2026'],
    ## ['argentina', 'Argentina', 'NA', 'January 17, 2026'],
    ## ['duluth', 'Duluth', 'NA', 'January 17, 2026'],
    ## ['puerto-rico', 'Puerto Rico', 'NA', 'January 24, 2026'],
    ## ['toronto', 'Toronto', 'NA', 'February 14, 2026'],
    
    ## The link will need testing
    # ['san-jose-cr', 'Costa Rica', 'NA', 'February 21, 2026'],
    # ['philadelphia-pa', 'Philadelphia', 'NA', 'March 21, 2026'],

    
    ## ['modling-austria', 'Austria', 'EU', 'November 15, 2025'],
    ## ['italy', 'Italy', 'EU', 'December 13, 2025'],
    ## ['spain', 'Spain', 'EU', 'January 3, 2026'],
    ## ['france', 'France', 'EU', 'February 7, 2026'],
    
    ## These links will need testing
    # ['bochum', 'Germany', 'EU', 'February 21, 2026'],
    # ['greece', 'Greece', 'EU', 'March 7, 2026'],
    # ['manchester', 'United Kingdom', 'EU', 'March 21, 2026'],

    
    ## ['ho-chi-minh-city-vietnam', 'Vietnam', 'AO', 'November 2, 2025'],
    ## ['surabaya-indonesia', 'Indonesia', 'AO', 'November 16, 2025'],
    ## ['bcs2526-malaysia', 'Malaysia', 'AO', 'December 6, 2025'],
    ## ['manila', 'Philippines', 'AO', 'January 17, 2026'],
    ## ['singapore', 'Singapore', 'AO', 'January 24, 2026'],
    
    ## These links will need testing too
    # ['melbourne', 'Melbourne, Australia', 'AO', 'February 28, 2026'],
    # ['sydney', 'Sydney, Australia', 'AO', 'March 28, 2026'],
    # ['jakarta', 'Indonesia', 'AO', 'March 28, 2026']
]

In [3]:

# module_path = os.path.abspath(os.path.join('..'))
# if module_path not in sys.path:
#     sys.path.append(module_path)

from data_collection_pipeline import main as get_data
# from data_collection_pipeline import *

print("This may take a few minutes for each event. Please wait :  ^)")
for event in final_event_list:
    get_data(BASE_URL, event)
    # When finished, the data will be added to mongo db
    print('Fisnished: ', event[1])
    print('~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~')

This may take a few minutes for each event. Please wait :  ^)
faild on deck 5JFGX on try 1
faild on deck 2VMWP on try 1
0  empty decks collected
Fisnished:  Toronto
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

And just like that, we have ***loads*** of data in our data base. Time to get cracking.

Or well, it would be, but I ran into a few issues with the way the data was organized,
and so we did some data wrangling:
* converted rank and wins into ints for easier analysis, and updated the pipeline
* added information about when and where the event took place into the pipeline, so that data can be analyized over time
* added everything we have so far to one giant table as well

We did some webscrabing to get the date and location of every event for every region. Perhaps next year we can make a scraper to get the event specific URLS, so we can combine these 2 tables. Toss in a feature to automatically wake up a week after each event and look for the results, and we could have the makings of a sophisticated program on our hands. Let's not get too ahead of ourselves, though...


I decided that since there are still more events to do, I'd add these steps directly into function `get_data` above, so that this can automatically be applied on the events that were marked TODO at time of writing.

While doing some initial EDA, I noticed that there were some outliers from specific events. All of the Malaysian event lacked nation information, and the event in the Philippines seemes to have had an additional round. To make the data more uniform, I adjusted the data in the central and isolated data clusters. Information about it has been moved from below, in step 3, to a new file,

DataWranglingPartTwoBCS.ipynb

# Step 3: EDA

We're back from the wragling for a second shot at analysis, and I noticed that I couldn't find 'Two Of Us, Rhyme' in any decks. I felt like that card should have been included, so let's keep that in our minds moving forward, now that we can explore every event at once. Sureley one person had to play her, right?

Hmmm... How do winrates for bosses look over time? that could be interesting.

In [3]:
EVENT = 'duluth'
STAND_HEALS = [
    "Stealth Fiend, Amaviera",
    "Incorruptible Holy Light, Eufha",
    "Lady Healer of the Creaking World",
    "Invigorate Sage",
    "Zypsophila Fairy, Asher",
    "Two Of Us, Rhyme",
]
CRIT_HEALS = [
    'Cure Flare Dracokid',
    'Brilliant Floral, Uania',
    'Whistling Arrow of Recursion, Obifold',
    'Heartiness Tear Sorceress',
    'Alchemic Hedgehog',
    'Two Of Us, Flow',
]

DRAWS = [
    'Flare Veil Dragon',
    'Rouse Wildmaster, Riley',
    'Ameliorate Connector',
    'Protection Magic, Prorobi',
    'Serene Maiden, Lena',
    'Transparent Snowy Night, Beretoi',
]

REGALIS = [
    "Primordial Heartblaze",
    "Shroud in Darkness",
    "Sound of Wave",
    "Fire Regalis",
    "Union the Sky",
    "Protection: Twincast",
    "Radiance Caliburn",
    "Bracing Angel Ladder",
    "Forbidoll Surrogate",  "'Mysterious Joker' Joker",
    "Evergreen Transhpere", "'Homeroom-Ninja Mr. Shinobu' Mr. Shinobu",
    "Gratias Gradale",      "'Croket!' Croket",
]
REGALIS_MAP = {
    "Primordial Heartblaze": None,
    "Shroud in Darkness": None,
    "Sound of Wave": None,
    "Fire Regalis": None,
    "Union the Sky": None,
    "Protection: Twincast": None,
    "Radiance Caliburn": None,
    "Bracing Angel Ladder": None,
    "Forbidoll Surrogate": None,  
    "'Mysterious Joker' Joker": "Forbidoll Surrogate",
    "Evergreen Transhpere": None, 
    "'Homeroom-Ninja Mr. Shinobu' Mr. Shinobu": "Evergreen Transhpere",
    "Gratias Gradale": None,      
    "'Croket!' Croket": "Gratias Gradale",
}

In [4]:
# Connect to MongoDB
username = 'sjmichael17_db_user'
password = 'rVtL43eBjseB5XkS' # plz don't hack me bro ;-;
cluster_address = 'bcsproto.peazuyx.mongodb.net/?appName=BCSproto'

client = MongoClient(f'mongodb+srv://{username}:{password}@{cluster_address}')

db = client['main_table']
collection = db['test']

In [5]:
# Aggregate wins across the collection: total, average, and document count.
pipeline = [
	{'$group': {
		'_id': None,
		'avg_wins': {'$avg': '$wins'},
		'count': {'$sum': 1}
	}}
]

result = list(collection.aggregate(pipeline))
result

[{'_id': None, 'avg_wins': 2.9122925078510544, 'count': 4458}]

## How big was each event?

In [6]:
loc_pipe = [
    {'$group': {
        '_id': '$location',
        'total_players': {'$sum': 1}
    }}
]

result = list(collection.aggregate(loc_pipe))
result.sort(key=lambda x: x['total_players'], reverse=True)
result

[{'_id': 'Duluth', 'total_players': 504},
 {'_id': 'LA', 'total_players': 489},
 {'_id': 'Philippines', 'total_players': 441},
 {'_id': 'TX', 'total_players': 338},
 {'_id': 'Rosemont', 'total_players': 307},
 {'_id': 'Malaysia', 'total_players': 294},
 {'_id': 'Toronto', 'total_players': 284},
 {'_id': 'Singapore', 'total_players': 279},
 {'_id': 'France', 'total_players': 213},
 {'_id': 'Vietnam', 'total_players': 198},
 {'_id': 'BC', 'total_players': 193},
 {'_id': 'Indonesia', 'total_players': 184},
 {'_id': 'Austria', 'total_players': 164},
 {'_id': 'Mexico', 'total_players': 163},
 {'_id': 'Italy', 'total_players': 149},
 {'_id': 'Argentina', 'total_players': 100},
 {'_id': 'Puerto Rico', 'total_players': 86},
 {'_id': 'Spain', 'total_players': 72}]

Now it's a good time to create a dataset that only includes top performing decks,
so we can try and find what stands out between them and decks that don't get big prizing.

Filttiring by 6 wins or better seems appropriate. A lot of the decks where I hear 'Foo topped', they usually bubble in with 5 wins and then lose in top cut. If they can earn their 6th win, great, but plenty of decks with only 5 wins don't make top cut. There were about 100 players X-2 or greater after the end of round 7 in LA, so having most of the players with 5 wins not being in top cut, when we're trying to find topping lists doesn't seem appropriate.

In [7]:
full_df = pd.DataFrame(collection.find({}))
top_df= pd.DataFrame((collection.find({"wins": {"$gt": 5}})))

full_df.drop(columns=['_id'], inplace=True)
top_df.drop(columns=['_id'], inplace=True)

full_df.nation.unique()

array(['Dark States', 'Brandt Gate', 'Keter Sanctuary', 'Stoicheia',
       'Dragon Empire', 'BanG Dream!', 'Lyrical Monasterio', 'Buddyfight',
       'SHAMAN KING', 'Touken Ranbu'], dtype=object)

We can store this dataframe locally for laptop programming later

TODO :
'/Users/admin/BCSdata/BCSanalysis/.json'
Needs to be made programaic on the macbook

In [8]:
top_df.to_json(path.join('/Users/admin/BCSdata/BCSanalysis/.json','ToppingDecks.json'), orient='records')
full_df.to_json(path.join('/Users/admin/BCSdata/BCSanalysis/.json','AllDecks.json'), orient='records')

In [265]:
# lets test its loading for a sanity check
top_df = pd.read_json(path.join('.json','ToppingDecks.json'), orient='records')
# top_df = top_df.transpose()
top_df.head()

,rank,name,boss,wins,nation,decklog,deck,location,region,date
0,1,Champion,"Sugary and Scary Land, Heartluru",11,Dark States,2FJ64,"{'RideDeck': {'Sugary and Scary Land, Heartlur...",Rosemont,NA,2025-10-04
1,2,Champion,"Rewrite the Star, Vyrgilla",9,Dragon Empire,5WRMJ,"{'RideDeck': {'Rewrite the Star, Vyrgilla': 1,...",Rosemont,NA,2025-10-04
2,21,hosj,"Sugary and Scary Land, Heartluru",6,Dark States,511K6,"{'RideDeck': {'Sugary and Scary Land, Heartlur...",Rosemont,NA,2025-10-04
3,11,Nomad,"Rewrite the Star, Vyrgilla",7,Dragon Empire,2GHAG,"{'RideDeck': {'Rewrite the Star, Vyrgilla': 1,...",Rosemont,NA,2025-10-04
4,15,Entropy,"Sealed Blaze of Arbitration, Bavsargra Aksayya",7,Dragon Empire,3RVUG,"{'RideDeck': {'Sealed Blaze of Arbitration, Ba...",Rosemont,NA,2025-10-04

In [9]:
top_df.describe()

             rank        wins
count  336.000000  336.000000
mean    12.422619    7.056548
std      8.923219    1.311175
min      1.000000    6.000000
25%      5.000000    6.000000
50%     10.000000    7.000000
75%     18.000000    8.000000
max     38.000000   12.000000

In [267]:
# These notes are from unsaved code. They show the average win rate of decks grouped by nation, and number of S-C-H's, from 0, down to 4
"""
brandt
2.25
2.6
3.260869565217391
1.5
5

DE
2.652173913043478
3.0833333333333335
3.7142857142857144
4.5
4

DS
2.090909090909091
1.5
3.3157894736842106
2.5
3.1818181818181817

Lyrical bugged???

Stoi
2.1153846153846154
2.5714285714285716
2.5238095238095237
4.2
3.5

Keter
1.5
2.2857142857142856
2.875
2.6
2.5
"""

"""
Notes:
for every nation, playing 0 counter heals lowered the win rate to below the nations average.
    Playing 2 leads to better than average results,
except for stoi, who have better than average results for player 3+
Every nation, except brandt, has the best performing count at less than 4.
    It seems 2/3 should be good, unless you're brandt gate.
    Leaning twords 3 rn, since the brandt issue may be an outlier, and the others show decent growth.
        2 may be a bit more safe, but they're both better than 0, bar brandt gate.

Lyrical didn't turn up results for Rhyme... which is cause for concearn and investigation.
The next questions I have;
    How does the precence of draws affect things?
    How does the boss interact with heal stats?
    
"""

"\nNotes:\nfor every nation, playing 0 counter heals lowered the win rate to below the nations average.\n    Playing 2 leads to better than average results,\nexcept for stoi, who have better than average results for player 3+\nEvery nation, except brandt, has the best performing count at less than 4.\n    It seems 2/3 should be good, unless you're brandt gate.\n    Leaning twords 3 rn, since the brandt issue may be an outlier, and the others show decent growth.\n        2 may be a bit more safe, but they're both better than 0, bar brandt gate.\n\nLyrical didn't turn up results for Rhyme... which is cause for concearn and investigation.\nThe next questions I have;\n    How does the precence of draws affect things?\n    How does the boss interact with heal stats?\n\n"

## Next Up, the Mystery of Rhyme

Ok, Now with the Malaysia situation handled, we can return our focus to Rhyme. 
I recall from some early analysis that she didn't appear in my search when I expected her to, but I've found her as expected in some new searches. Let's do the analysis of heals starting with her, because we may kill 2 birds with one stone. 

We'll need to be very particular about the way we index into our decklists. They're;
* in the dataframe under the deck column
* are stored as a dictionary of 3 deck dictionaries;
    * RideDeck
    * MainDeck
    * GDeck
* Each of these deck dicts have the card name as the key, and the quantity played as the value

In [10]:
# Let's start with a helper function that kind find out if a card is in a deck
def card_is_in_deck(decks_dict, card_name, deck='MainDeck'):
    return card_name in decks_dict[deck]


def card_count_in_deck(decks_dict, card_name, deck='MainDeck'):
    return decks_dict[deck].get(card_name, 0)


# This function combines the former two, and allows a list of cards as input
def card_type_in_deck(decks_dict, card_list, deck='MainDeck'):
    for card in card_list:
        if card_is_in_deck(decks_dict, card, deck):
            return card_count_in_deck(decks_dict, card, deck)
        
    return 0

def extract_regalis(decks_dict, regalis_list):
    for card_name in regalis_list:
        if card_is_in_deck(decks_dict, card_name):
            if REGALIS_MAP[card_name] != None:
                return REGALIS_MAP[card_name]
            else:
                return card_name
        
    return "None"

In [42]:
name = "Two Of Us, Rhyme"
dfLyrical = full_df[full_df['nation'] == 'Lyrical Monasterio']

# dfLyrical.boss.unique()
dfLyrical.loc[:,'count'] = dfLyrical.deck.apply(lambda deck: card_count_in_deck(deck, name))

# dfLyrical.sort_values('count', inplace=True)
dfLyrical.location.unique()

C:\Users\Mimi\AppData\Local\Temp\ipykernel_19296\3794117284.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  dfLyrical.loc[:,'count'] = dfLyrical.deck.apply(lambda deck: card_count_in_deck(deck, name))

array(['Rosemont', 'Mexico', 'TX', 'LA', 'BC', 'Argentina', 'Duluth',
       'Puerto Rico', 'Austria', 'Italy', 'Spain', 'France', 'Vietnam',
       'Indonesia', 'Malaysia', 'Singapore', 'Philippines', 'Toronto'],
      dtype=object)

Hm, no, looks like after we got the data and our code in order, at least one person eat each event was playing Rhyme.

The issue was probably my poor coding, or even more likely, my poor attention to the name string; but at least it's led to me doing some good coding, and using this above code to expand to use a list of names, instead of just Rhyme, so now we can do analysis on all the data!

This is the results from some prelimiary heal type analysis

In [ ]:
top_df.loc[:,'stand_heal_count']   = top_df.deck.apply(lambda deck: card_type_in_deck(deck, STAND_HEALS))
full_df.loc[:,'stand_heal_count'] = full_df.deck.apply(lambda deck: card_type_in_deck(deck, STAND_HEALS))

top_df.loc[:,'crit_heal_count']    = top_df.deck.apply(lambda deck: card_type_in_deck(deck, CRIT_HEALS))
full_df.loc[:,'crit_heal_count']  = full_df.deck.apply(lambda deck: card_type_in_deck(deck, CRIT_HEALS))

top_df.loc[:,'draw_count']         = top_df.deck.apply(lambda deck: card_type_in_deck(deck, REGALIS))
full_df.loc[:,'draw_count']       = full_df.deck.apply(lambda deck: card_type_in_deck(deck, REGALIS))

top_df.loc[:, 'regalis_piece']     = top_df.deck.apply(lambda deck: extract_regalis(deck, REGALIS))
full_df.loc[:, 'regalis_piece']   = full_df.deck.apply(lambda deck: extract_regalis(deck, REGALIS))

# top_df.sort_values('rank', inplace=True)
# top_df.head()

In [12]:
print(
    top_df['stand_heal_count'].mean(), '\n',
    top_df['crit_heal_count'].mean(), '\n',
    top_df['draw_count'].mean(), '\n',
    top_df['wins'].mean(),   '\n',
)

1.943452380952381
 0.125
 0.9434523809523809
 7.056547619047619

In [13]:
# Now we can compare the top performers to the whole population
print(
    full_df['stand_heal_count'].mean(), '\n',
    full_df['crit_heal_count'].mean(), '\n',
    full_df['draw_count'].mean(), '\n',
    full_df['wins'].mean(),   '\n',
)

1.1128308658591297
 0.14445939883355766
 0.857335127860027
 2.9122925078510544

In [ ]:
top_df.groupby('stand_heal_count').describe().loc[:, (slice(None), ['count', 'mean', 'std'])]

                   rank                        wins                      \
                  count       mean       std  count      mean       std
stand_heal_count
0                  58.0  13.189655  9.304700   58.0  7.017241  1.344141
1                  29.0  13.344828  9.247686   29.0  6.862069  1.274030
2                 174.0  12.402299  8.623077  174.0  6.977011  1.201896
3                  24.0  11.833333  9.365369   24.0  7.333333  1.464557
4                  51.0  11.372549  9.316568   51.0  7.352941  1.546913

                 crit_heal_count                     draw_count            \
                           count      mean       std      count      mean
stand_heal_count
0                           58.0  0.000000  0.000000       58.0  0.965517
1                           29.0  0.344828  0.483725       29.0  0.862069
2                          174.0  0.166667  0.527655      174.0  0.948276
3                           24.0  0.125000  0.337832       24.0  0.916667
4                           51.0  0.000000  0.000000       51.0  0.941176


                       std
stand_heal_count
0                 0.184059
1                 0.350931
2                 0.222109
3                 0.282330
4                 0.237635

In [24]:
full_df.groupby('stand_heal_count').describe().loc[:, (slice(None), ['count', 'mean', 'std'])]

                    rank                            wins                      \
                   count        mean         std   count      mean       std
stand_heal_count
0                 2017.0  183.741200  120.116723  2017.0  2.380268  1.732528
1                  566.0  155.929329  117.402230   566.0  2.839223  1.834946
2                 1484.0  129.869946  108.543306  1484.0  3.440027  2.000280
3                  137.0  141.839416  122.763776   137.0  3.445255  2.470174
4                  254.0  116.421260  103.209444   254.0  3.929134  2.293421

                 crit_heal_count                     draw_count            \
                           count      mean       std      count      mean
stand_heal_count
0                         2017.0  0.079326  0.361399     2017.0  0.774913
1                          566.0  0.439929  0.544413      566.0  0.888693
2                         1484.0  0.144205  0.483818     1484.0  0.926550
3                          137.0  0.153285  0.361584      137.0  0.934307
4                          254.0  0.000000  0.000000      254.0  0.948819


                       std
stand_heal_count
0                 0.417743
1                 0.314791
2                 0.260962
3                 0.248655
4                 0.238031

Hm! From this, it's quite clear that topping decks play more counter heals than average.

Most players seem to playing about one on average, whereas top players are playing about two.
Or, well it was clear, then I overwrote the queries....

Before, they were grouped by nation, now, They're grouped by their count of counter heals

This, too, tells us something. Decks with no counter heals have a lower rate on overage than decks that do. 
Even playing 1 can make an impact it seems! Playing 4 gives the best results, it seems, with a tiny tip at 3?
Three count was our lowest sample size, so maybe it's just noise. The average winrate is very similar to two.

However, in top cut, there's a sort of 'reverse curve', where playing 1 or 2 decreases the win rate compared to 0,
but having 3 and 4 shoots it back up with each additional card you ad.

This may suggest that while the inclusion of counter heals is a good idea in general, some decks or playstyles may benifit from having vanilla triggers

After a tune up of the above code, we can also see that the Crit-Counter-Heals are very rarely played, and even a bit rarer still in top cut.

It would also seem most deck aren't playing draws, considering the average is less than 1.
This tracks with some data from VG paradox, which showed that for most nations, the most played generic card were shield-front triggers.

Now, I'd like to see more info about how many draws people are playing. Maybe some people are just splashing one or two? How many players are playing 4?

In [289]:
testDF = full_df.drop(columns=['rank'])
testDF.loc[:, 'both_heals'] = (testDF['stand_heal_count'] > 0) & (testDF['crit_heal_count'] > 0)
testDF.groupby('both_heals').describe().loc[:, (slice(None), ['count', 'mean', 'std'])]

              wins                     stand_heal_count                      \
             count      mean       std            count      mean       std
both_heals
False       3808.0  2.925420  1.970682           3808.0  1.052258  1.213985
True         366.0  2.844262  1.890222            366.0  1.431694  0.591706

           crit_heal_count                     draw_count
                     count      mean       std      count      mean       std
both_heals
False               3808.0  0.040704  0.262682     3808.0  0.768908  1.283816
True                 366.0  1.232240  0.441850      366.0  0.754098  1.286249

In [290]:
testDF.groupby('crit_heal_count').describe().loc[:, (slice(None), ['count', 'mean', 'std'])]

                   wins                     stand_heal_count            \
                  count      mean       std            count      mean
crit_heal_count
0                3700.0  2.947568  1.977696           3700.0  1.082973
1                 353.0  2.682720  1.760088            353.0  1.042493
2                 112.0  2.812500  2.081801            112.0  1.366071
3                   7.0  1.571429  0.975900              7.0  0.428571
4                   2.0  1.000000  1.414214              2.0  0.000000

                          draw_count
                      std      count      mean       std
crit_heal_count
0                1.217997     3700.0  0.760270  1.277878
1                0.735393      353.0  0.844193  1.323338
2                0.910356      112.0  0.741071  1.347307
3                0.534522        7.0  1.000000  1.414214
4                0.000000        2.0  1.500000  2.121320

In [291]:
testDF = testDF[testDF['stand_heal_count'] > 0]
foo = testDF.drop(columns=['draw_count'])
foo.groupby('both_heals').describe().loc[:, (slice(None), ['count', 'mean', 'std'])]

              wins                     stand_heal_count                      \
             count      mean       std            count      mean       std
both_heals
False       1880.0  3.464362  2.057659           1880.0  2.131383  0.827465
True         366.0  2.844262  1.890222            366.0  1.431694  0.591706

           crit_heal_count
                     count     mean      std
both_heals
False               1880.0  0.00000  0.00000
True                 366.0  1.23224  0.44185

Alicia and Nina asked for a bit more clarification about how the crit heals peformed. Turns out; not well. Playing more of the crit heal seems to decrease winrate.

The data shows a slight tick up when players are playing 2 crit-heals, but looking at the rest of the statistics tells me that this is potentially due to the fact that this row has the highest mean of stand-heals, and lowest mean of draw triggers, both of which are associated with higher winrates. 

It seems less that the 2 crit-heals were putting in work, and more that the 2 stand-heals and fronts these players were playing with put in more.

In [295]:
shieldDF = top_df.drop(columns=['rank', 'date'])
shieldDF.loc[:,'low_shield_count'] = (shieldDF['stand_heal_count']) + (shieldDF['crit_heal_count']) + (shieldDF['draw_count'])
shieldDF.groupby('low_shield_count').describe().loc[:, (slice(None), ['count', 'mean', 'std'])]

                   wins                     stand_heal_count            \
                  count      mean       std            count      mean
low_shield_count
0                  36.0  7.111111  1.389302             36.0  0.000000
1                  14.0  7.571429  1.452546             14.0  1.000000
2                 114.0  6.947368  1.203550            114.0  1.903509
3                  33.0  6.818182  1.184656             33.0  1.272727
4                  68.0  7.029412  1.315472             68.0  3.220588
5                  32.0  7.250000  1.319824             32.0  2.000000
6                   6.0  9.000000  2.000000              6.0  2.666667
7                   6.0  7.166667  1.169045              6.0  3.666667

                           crit_heal_count                     draw_count  \
                       std           count      mean       std      count
low_shield_count
0                 0.000000            36.0  0.000000  0.000000       36.0
1                 0.000000            14.0  0.000000  0.000000       14.0
2                 0.325040           114.0  0.061404  0.241129      114.0
3                 1.442063            33.0  0.060606  0.242306       33.0
4                 1.005145            68.0  0.264706  0.660566       68.0
5                 0.439941            32.0  0.093750  0.296145       32.0
6                 0.816497             6.0  0.333333  0.516398        6.0
7                 0.816497             6.0  0.333333  0.816497        6.0


                      mean       std
low_shield_count
0                 0.000000  0.000000
1                 0.000000  0.000000
2                 0.035088  0.227718
3                 1.666667  1.493039
4                 0.514706  0.922240
5                 2.906250  0.390151
6                 3.000000  0.632456
7                 3.000000  0.000000

This result above is kind of useless? like, ofc decks with more than 4 low sield cards have draws. We need to think up a way to better ask this query.

In [294]:
shieldDF = full_df.drop(columns=['rank'])
shieldDF.loc[:,'low_shield_count'] = (shieldDF['stand_heal_count']) + (shieldDF['crit_heal_count']) + (shieldDF['draw_count'])
shieldDF.groupby('low_shield_count').describe().loc[:, (slice(None), ['count', 'mean', 'std'])]

                    wins                     stand_heal_count            \
                   count      mean       std            count      mean
low_shield_count
0                 1302.0  2.390169  1.725113           1302.0  0.000000
1                  297.0  2.861953  1.946358            297.0  0.713805
2                 1152.0  3.269097  1.974771           1152.0  1.690104
3                  519.0  2.755299  1.900987            519.0  0.697495
4                  511.0  3.305284  2.118257            511.0  2.328767
5                  277.0  3.328520  2.094770            277.0  1.823105
6                   66.0  3.469697  2.315298             66.0  2.363636
7                   42.0  3.738095  2.060778             42.0  3.214286
8                    8.0  3.250000  1.832251              8.0  3.000000

                           crit_heal_count                     draw_count  \
                       std           count      mean       std      count
low_shield_count
0                 0.000000          1302.0  0.000000  0.000000     1302.0
1                 0.452745           297.0  0.144781  0.352474      297.0
2                 0.621346          1152.0  0.167535  0.421682     1152.0
3                 1.119765           519.0  0.123314  0.383310      519.0
4                 1.446271           511.0  0.362035  0.727639      511.0
5                 0.584622           277.0  0.209386  0.465691      277.0
6                 1.061731            66.0  0.363636  0.671081       66.0
7                 1.094013            42.0  0.738095  1.083345       42.0
8                 0.925820             8.0  1.000000  0.925820        8.0


                      mean       std
low_shield_count
0                 0.000000  0.000000
1                 0.141414  0.349036
2                 0.142361  0.504242
3                 2.179191  1.253824
4                 1.309198  1.457332
5                 2.967509  0.354615
6                 3.272727  0.795090
7                 3.047619  0.215540
8                 4.000000  0.000000

In [49]:
pd.set_option('display.max_rows', None)

# Show all columns
pd.set_option('display.max_columns', None)

In [44]:
foo = top_df.groupby('regalis_piece').describe().loc[:, (slice(None), ['count','mean', 'std'])]
foo.sort_values(('wins', 'mean'))

                       rank                        wins                      \
                      count       mean       std  count      mean       std
regalis_piece
Forbidoll Surrogate     2.0  11.500000  4.949747    2.0  6.000000  0.000000
Gratias Gradale         1.0  33.000000       NaN    1.0  6.000000       NaN
None                   19.0  13.421053  7.690657   19.0  6.526316  0.772328
Shroud in Darkness     18.0  16.222222  9.625674   18.0  6.666667  0.907485
Protection: Twincast  151.0  12.754967  8.975498  151.0  6.973510  1.280349
Union the Sky          25.0  12.440000  9.966945   25.0  7.040000  1.059874
Fire Regalis           90.0  11.766667  8.713995   90.0  7.244444  1.440280
0                       4.0  12.250000  9.535023    4.0  7.250000  1.892969
Radiance Caliburn      11.0  11.090909  7.489386   11.0  7.272727  1.489356
Bracing Angel Ladder   15.0   6.933333  7.166058   15.0  7.933333  1.533747

                     stand_heal_count                     crit_heal_count  \
                                count      mean       std           count
regalis_piece
Forbidoll Surrogate               2.0  2.000000  0.000000             2.0
Gratias Gradale                   1.0  0.000000       NaN             1.0
None                             19.0  2.105263  1.100239            19.0
Shroud in Darkness               18.0  1.611111  0.849837            18.0
Protection: Twincast            151.0  2.000000  1.160460           151.0
Union the Sky                    25.0  1.400000  1.258306            25.0
Fire Regalis                     90.0  2.133333  1.228866            90.0
0                                 4.0  1.500000  1.914854             4.0
Radiance Caliburn                11.0  1.727273  1.737292            11.0
Bracing Angel Ladder             15.0  1.733333  1.162919            15.0

                                         draw_count
                          mean       std      count mean  std
regalis_piece
Forbidoll Surrogate   0.000000  0.000000        2.0  1.0  0.0
Gratias Gradale       0.000000       NaN        1.0  1.0  NaN
None                  0.157895  0.374634       19.0  0.0  0.0
Shroud in Darkness    0.444444  0.783823       18.0  1.0  0.0
Protection: Twincast  0.099338  0.378681      151.0  1.0  0.0
Union the Sky         0.120000  0.331662       25.0  1.0  0.0
Fire Regalis          0.111111  0.435618       90.0  1.0  0.0
0                     0.000000  0.000000        4.0  1.0  0.0
Radiance Caliburn     0.090909  0.301511       11.0  1.0  0.0
Bracing Angel Ladder  0.133333  0.516398       15.0  1.0  0.0

In [45]:
foo = full_df.groupby('regalis_piece').describe().loc[:, (slice(None), ['count','mean', 'std'])]
foo.sort_values(('wins', 'mean'))

                         rank                            wins            \
                        count        mean         std   count      mean
regalis_piece
Sound of Wave            16.0  273.250000  131.813758    16.0  1.625000
Primordial Heartblaze    26.0  216.115385  124.527050    26.0  1.846154
Gratias Gradale           6.0  261.000000  140.662717     6.0  2.000000
None                    637.0  188.141287  119.561853   637.0  2.193093
0                        69.0  189.797101  118.373608    69.0  2.217391
Forbidoll Surrogate      86.0  197.453488  135.311463    86.0  2.302326
Radiance Caliburn       320.0  172.181250  114.163518   320.0  2.534375
Bracing Angel Ladder    214.0  160.042056  110.904786   214.0  2.822430
Evergreen Transhpere      2.0  152.500000   84.145707     2.0  3.000000
Shroud in Darkness      235.0  149.063830  113.046811   235.0  3.038298
Fire Regalis           1072.0  150.888060  116.179280  1072.0  3.042910
Union the Sky           230.0  134.139130  111.943130   230.0  3.173913
Protection: Twincast   1545.0  143.576699  116.328219  1545.0  3.250485

                                stand_heal_count                      \
                            std            count      mean       std
regalis_piece
Sound of Wave          1.408309             16.0  0.250000  0.774597
Primordial Heartblaze  1.347362             26.0  0.538462  0.760567
Gratias Gradale        2.280351              6.0  0.833333  1.329160
None                   1.683834            637.0  0.554160  0.951151
0                      1.969395             69.0  0.478261  0.994229
Forbidoll Surrogate    1.645456             86.0  0.860465  1.042201
Radiance Caliburn      1.736228            320.0  0.850000  1.086826
Bracing Angel Ladder   2.102148            214.0  0.929907  1.100466
Evergreen Transhpere   1.414214              2.0  2.000000  2.828427
Shroud in Darkness     1.865860            235.0  1.085106  1.082688
Fire Regalis           2.045246           1072.0  1.356343  1.204519
Union the Sky          2.001139            230.0  1.143478  1.200919
Protection: Twincast   1.988318           1545.0  1.314563  1.220274

                      crit_heal_count                     draw_count  \
                                count      mean       std      count
regalis_piece
Sound of Wave                    16.0  0.375000  0.718795       16.0
Primordial Heartblaze            26.0  0.076923  0.271746       26.0
Gratias Gradale                   6.0  0.333333  0.816497        6.0
None                            637.0  0.155416  0.485017      637.0
0                                69.0  0.115942  0.322501       69.0
Forbidoll Surrogate              86.0  0.174419  0.489702       86.0
Radiance Caliburn               320.0  0.171875  0.446326      320.0
Bracing Angel Ladder            214.0  0.233645  0.557988      214.0
Evergreen Transhpere              2.0  0.000000  0.000000        2.0
Shroud in Darkness              235.0  0.157447  0.448999      235.0
Fire Regalis                   1072.0  0.131530  0.415001     1072.0
Union the Sky                   230.0  0.121739  0.377253      230.0
Protection: Twincast           1545.0  0.130097  0.418833     1545.0


                           mean       std
regalis_piece
Sound of Wave          1.000000  0.000000
Primordial Heartblaze  1.000000  0.000000
Gratias Gradale        1.000000  0.000000
None                   0.000000  0.000000
0                      1.000000  0.000000
Forbidoll Surrogate    1.000000  0.000000
Radiance Caliburn      1.000000  0.000000
Bracing Angel Ladder   1.000000  0.000000
Evergreen Transhpere   1.000000  0.000000
Shroud in Darkness     1.000000  0.000000
Fire Regalis           1.000000  0.000000
Union the Sky          1.000000  0.000000
Protection: Twincast   1.000647  0.025441

In [14]:
import seaborn

In [16]:
foo = full_df.groupby(['date']).describe().loc[:, (slice(None), ['count','mean', 'std'])]
foo.drop(columns=['rank', 'crit_heal_count', 'draw_count'], inplace=True)
# foo = foo.reset_index()
seaborn.lineplot(data=foo, x='date,', y=('wins', 'mean'))

ValueError: Could not interpret value `date,` for `x`. An entry with this name does not appear in `data`.