Input Boss Name

Get boss's data from db

seperate data into decks with 6+ wins, and decks with less

Create a dictionary for each set of performers

sum up all the cards from each deck into their respective dicts

Take the average of everything

In [1]:

from collections import defaultdict

import card_data_collection_pipeline
import db_operations
import helpers

import pandas as pd

In [ ]:

def db_lookup(id_and_name):
    id = helpers.extract_card_id(id_and_name)
    return db_operations.find_first_in_table('main_table', 'card_data', {'id':id})


def url_lookup(id_and_name):
    id = helpers.extract_card_id(id_and_name)
    return card_data_collection_pipeline.add_card_info_to_db(id)

In [3]:
BOSS_NAME = "Rewrite the Star, Vyrgilla"

In [4]:
full_df = db_operations.get_answer_from_table(database='main_table',
                                              table='all_events',
                                              query={'boss':
                                                     {'$regex':BOSS_NAME}
                                                     }
                                             )

In [5]:
full_df.head()

,_id,rank,name,boss,wins,nation,decklog,deck,location,region,date
0,69b018213efa47b42b6c188b,2,Champion,"DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla",9,Dragon Empire,5WRMJ,{'RideDeck': {'DZ-SS04/001EN-R : Rewrite the S...,Rosemont,NA,"October 4, 2025"
1,69b018213efa47b42b6c188e,5,Ryuta,"DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla",8,Dragon Empire,57S3E,{'RideDeck': {'DZ-SS04/001EN-R : Rewrite the S...,Rosemont,NA,"October 4, 2025"
2,69b018213efa47b42b6c1891,8,TKS|RedX,"DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla",8,Dragon Empire,7T6BW,{'RideDeck': {'DZ-SS04/001EN-R : Rewrite the S...,Rosemont,NA,"October 4, 2025"
3,69b018213efa47b42b6c1892,9,Josh.,"DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla",8,Dragon Empire,6Q7SL,{'RideDeck': {'DZ-SS04/001EN-R : Rewrite the S...,Rosemont,NA,"October 4, 2025"
4,69b018213efa47b42b6c1894,11,Nomad,"DZ-BT02/FR05EN : Rewrite the Star, Vyrgilla",7,Dragon Empire,2GHAG,{'RideDeck': {'DZ-BT02/FR05EN : Rewrite the St...,Rosemont,NA,"October 4, 2025"

Currently, I'm noticing two bugs with the system.
One: Alphnights keeps getting added to the db again and again, so it's failing to read??
Also noticed maybe the same thing with hakasui and remred?

Two: Most cards with no flavor text have an issue with the format~artist 'line'

In [ ]:
# lets try just saving and re loading one copy of alphknights. If we can do one, we can do more :)

In [6]:
for i, row in full_df.iterrows():
    new_deck = defaultdict(int)
    for card_id_and_name, amount in row.deck['MainDeck'].items():
        # print(card_id_and_name,'\n', amount,'\n~~~~~~~~~~~~~~~~~~~~~~')
        # if type(amount) != type(67):
        #     print(type(amount))
        lookup = db_lookup(card_id_and_name)
        if not lookup:
            lookup = url_lookup( card_id_and_name)

        name = lookup['name']

        if 'Trigger' in lookup['type']:
            if 5000 == lookup['power']:
                name = 'Vanilla Trigger'

        if '[CONT]Sentinel' in lookup['effect']:
            if 'Unit' in lookup['type']:
                name = 'Sentinel'
            else:
                name = 'Elementaria'

        new_deck[name] += amount
    
    full_df.at[i, 'deck']['MainDeck'] = new_deck

KeyboardInterrupt:

In [ ]:
# foo = card_data_collection_pipeline.get_card_info_from_bushi_site('DZ-SS08/007EN')
# foo

['Vyrgilla, "Rewrite Form: Alfknights"',
 'Normal Unit\nDragon Empire\nCyber Dragon\nGrade 3\nPower 13000\nCritical 1\nShield -\nTwin Drive!!, Persona Ride',
 '[Rewrite] - [ACT](Hand):If your opponent\'s vanguard is grade 3 or greater, [COST][bind a "Rewrite the Star, Vyrgilla" on (VC)], ride this card as [Stand], and perform all of the following. At the end of that turn, ride the card bound for this cost as [Rest]. ・Search your deck or drop for up to one <Galaxian>, call it to (RC), search your deck or drop for up to one Ultimate Skill card, reveal it and put it into hand, and if you searched the deck, shuffle the deck. ・Until end of turn, this unit gets "[AUTO](VC)[1/Turn]:When this unit attacks, [COST][Counter-Blast 1], [Stand] all of your front row rear-guards, and this unit gets drive +1 until end of that battle.", and all of your front row units get [Power]+5000 for each card with the same card name as this unit in your soul.',
 'With bonds in its heart, the dragon rewrites itself.\r\nInto the king that commands the knights!',
 'Standard\nDZ-SS08/007EN\nRRR\n©大円坊 真／小学館\u3000unitdesign:伊藤彰']

In [ ]:
full_df.head()

,_id,rank,name,boss,wins,nation,decklog,deck,location,region,date
0,69b018213efa47b42b6c188b,2,Champion,"DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla",9,Dragon Empire,5WRMJ,{'RideDeck': {'DZ-SS04/001EN-R : Rewrite the S...,Rosemont,NA,"October 4, 2025"
1,69b018213efa47b42b6c188e,5,Ryuta,"DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla",8,Dragon Empire,57S3E,{'RideDeck': {'DZ-SS04/001EN-R : Rewrite the S...,Rosemont,NA,"October 4, 2025"
2,69b018213efa47b42b6c1891,8,TKS|RedX,"DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla",8,Dragon Empire,7T6BW,{'RideDeck': {'DZ-SS04/001EN-R : Rewrite the S...,Rosemont,NA,"October 4, 2025"
3,69b018213efa47b42b6c1892,9,Josh.,"DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla",8,Dragon Empire,6Q7SL,{'RideDeck': {'DZ-SS04/001EN-R : Rewrite the S...,Rosemont,NA,"October 4, 2025"
4,69b018213efa47b42b6c1894,11,Nomad,"DZ-BT02/FR05EN : Rewrite the Star, Vyrgilla",7,Dragon Empire,2GHAG,{'RideDeck': {'DZ-BT02/FR05EN : Rewrite the St...,Rosemont,NA,"October 4, 2025"

In [ ]:
top_df = full_df[full_df['wins'] > 5]
bot_df = full_df[full_df['wins'] <= 5]

In [ ]:

top_dict = defaultdict(int)
bot_dict = defaultdict(int)
all_dict = defaultdict(int)

for dict in top_df.deck:
    for k, v in dict['MainDeck'].items():
        top_dict[k] += v
        all_dict[k] += v

for dict in bot_df.deck:
    for k, v in dict['MainDeck'].items():
        bot_dict[k] += v
        all_dict[k] += v

In [ ]:
num_tops = len(top_df)
num_bots = len(bot_df)
num_total = num_tops + num_bots

print("Number of Tops: ", num_tops)
print("Number of Bots: ", num_bots)
print("Total Number: ", num_total)

Number of Tops:  74
Number of Bots:  456
Total Number:  530

In [ ]:
top_dict = {k: v / num_tops for k,v in top_dict.items()}
bot_dict = {k: v / num_bots for k,v in bot_dict.items()}
all_dict = {k: v / num_total for k,v in all_dict.items()}

top_dict = {k:v for k,v in sorted(top_dict.items(), key=lambda k: k[1], reverse=True)}
bot_dict = {k:v for k,v in sorted(bot_dict.items(), key=lambda k: k[1], reverse=True)}
all_dict = {k:v for k,v in sorted(all_dict.items(), key=lambda k: k[1], reverse=True)}

In [ ]:
top_dict

{"DZ-SS08/007EN : Vyrgilla, 'Rewrite Form: Alfknights'": 3.635135135135135,
 'DZ-BT08/003EN : Dragritter, Nirmihn': 3.2972972972972974,
 'DZ-SS04/006EN : Ezerwur': 1.837837837837838,
 'D-PR/333EN : Stealth Fiend, Shenryi': 1.6756756756756757,
 'DZ-SS09/007EN : Ezerwur': 1.3783783783783783,
 'DZ-SS09/011EN : Flare Cosmor': 1.337837837837838,
 'DZ-SS01/Re05EN : Stealth Fiend, Amaviera': 1.0810810810810811,
 'D-PR/725EN : Variance Ray Dragon': 0.9864864864864865,
 'D-BT05/022EN : Stealth Fiend, Amaviera': 0.8513513513513513,
 'DZ-SS09/010EN : Stealth Fiend, Shenryi': 0.8513513513513513,
 'DZ-SS04/005EN : Flag-raising of Courage, Fanvare': 0.8243243243243243,
 'DZ-SS01/Re37EN : Stealth Fiend, Shenryi': 0.8243243243243243,
 'DZ-SS08/001EN : Dragritter, Miqdard': 0.7432432432432432,
 'DZ-SS04/011EN : Twin Buckler Dragon': 0.7297297297297297,
 'DZ-SS09/019EN : Blazing Star Cross': 0.7162162162162162,
 'D-BT11/065EN : Defensing Roar': 0.7162162162162162,
 'DZ-SS09/006EN : Flag-raising of Courage, Fanvare': 0.6756756756756757,
 'DZ-SS09/001EN-R : Rewrite the Star, Vyrgilla': 0.6486486486486487,
 'DZ-SS04/017EN-R : Stardust Blade': 0.6081081081081081,
 'D-BT02/030EN : Blaze Maiden, Parama': 0.581081081081081,
 'DZ-SS09/001EN : Rewrite the Star, Vyrgilla': 0.5675675675675675,
 'DZ-BT08/SR03EN : Dragritter, Nirmihn': 0.5405405405405406,
 'DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla': 0.5,
 'DZ-BT01/003EN : Dragritter, Falhart': 0.4864864864864865,
 'DZ-BT03/043EN : Protection: Twincast': 0.47297297297297297,
 'DZ-BT05/003EN : Summit Flare Dragon': 0.4594594594594595,
 'D-BT04/034EN : Flare Veil Dragon': 0.4594594594594595,
 'DZ-SS09/014EN : Rogue Beast, Sunegosuri': 0.4594594594594595,
 'D-SS09/008EN-R : Stealth Dragon, Utsuroi': 0.43243243243243246,
 'D-SS01/008EN : Blaze Maiden, Zonne': 0.43243243243243246,
 'D-BT03/030EN : Burning Flail Dragon': 0.4189189189189189,
 'DZ-SS09/007EN-R : Ezerwur': 0.4189189189189189,
 'DZ-SS04/001EN : Rewrite the Star, Vyrgilla': 0.40540540540540543,
 'DZ-SS09/009EN : Opening of the End, Enwing': 0.3918918918918919,
 'DZ-BT03/046EN : Blaze Maiden, Parama': 0.3918918918918919,
 'DZ-SS04/006EN-R : Ezerwur': 0.36486486486486486,
 "DZ-SS08/FFR01EN : Vyrgilla, 'Rewrite Form: Alfknights'": 0.36486486486486486,
 'DZ-SS09/006EN-R : Flag-raising of Courage, Fanvare': 0.35135135135135137,
 'D-SS05/Re04EN : Blaze Maiden, Parama': 0.33783783783783783,
 'DZ-SS09/011EN-R : Flare Cosmor': 0.33783783783783783,
 'DZ-BT01/054EN : Guardian Monk of Raging Flames, Monju': 0.32432432432432434,
 'DZ-SS04/013EN : Rogue Beast, Sunegosuri': 0.32432432432432434,
 'D-SS09/013EN : Stealth Dragon, Madowazu': 0.3108108108108108,
 'D-SS12/093EN : Blaze Maiden, Parama': 0.3108108108108108,
 'D-SS05/Re06EN : Flare Veil Dragon': 0.2972972972972973,
 'D-SS09/008EN : Stealth Dragon, Utsuroi': 0.2972972972972973,
 'D-PR/413EN : New Horizons, Yumenokessho POPY': 0.2972972972972973,
 'D-PR/726EN : Variance Ray Dragon': 0.28378378378378377,
 'DZ-SS09/019EN-R : Blazing Star Cross': 0.28378378378378377,
 'DZ-SS05/098EN : Nusa~~': 0.2702702702702703,
 'DZ-BT07/055EN : Burning Flail Dragon': 0.24324324324324326,
 'DZ-SS01/028EN : Rogue Beast, Sunegosuri': 0.24324324324324326,
 'DZ-SS09/009EN-R : Opening of the End, Enwing': 0.24324324324324326,
 'DZ-BT02/FR05EN : Rewrite the Star, Vyrgilla': 0.24324324324324326,
 'DZ-SS08/032EN : Blaze War Monk, Sougyou': 0.24324324324324326,
 'DZ-SS05/037EN : Are You Trying To Kill Me~~~~!!!!': 0.22972972972972974,
 'D-PR/WO01EN : Stealth Fiend, Souko': 0.22972972972972974,
 'D-SS09/016EN : Stealth Dragon, Shikintan': 0.22972972972972974,
 'DZ-SS09/018EN : Stardust Blade': 0.22972972972972974,
 'BCS2526/VGS01 : Guardian Monk of Raging Flames, Monju': 0.22972972972972974,
 'D-SS05/Re05EN : Burning Flail Dragon': 0.21621621621621623,
 'DZ-BT03/044EN : Burning Flail Dragon': 0.21621621621621623,
 'DZ-BT07/070EN : Guardian Monk of Raging Flames, Monju': 0.21621621621621623,
 'DZ-BT07/152EN : Light Elemental, Pachiri': 0.21621621621621623,
 'D-PR/803EN : Having Fun at Round1, Nao Inabe': 0.21621621621621623,
 'DZ-SS10/020EN : Protection: Twincast': 0.20270270270270271,
 'D-BT01/SP13EN : Dragon Deity King of Resurgence, Dragveda': 0.20270270270270271,
 'DZ-SS04/016EN : Refreshing Wind Dragon, Dinobreeze': 0.20270270270270271,
 'DZ-SS04/005EN-R : Flag-raising of Courage, Fanvare': 0.20270270270270271,
 'D-BT01/031EN : Twin Buckler Dragon': 0.20270270270270271,
 'D-PR/289EN : Yumenokessho ROSE': 0.20270270270270271,
 'DZ-BT01/FR08EN : Guardian Monk of Raging Flames, Monju': 0.1891891891891892,
 'DZ-SS05/034EN : Cold Noodles Are Gone': 0.1891891891891892,
 'D-BT03/SP36EN : Burning Flail Dragon': 0.1891891891891892,
 'DZ-SS09/013EN : Dragon Deity King of Resurgence, Dragveda': 0.1891891891891892,
 'D-SS12/092EN : Flare Veil Dragon': 0.17567567567567569,
 'DZ-BT07/056EN : Flare Veil Dragon': 0.17567567567567569,
 'D-SS12/SIR18EN : Blaze Maiden, Parama': 0.17567567567567569,
 'D-SD01/014EN : Blaze Maiden, Rona': 0.16216216216216217,
 "DZ-SS05/CR02EN : 'Butto Bird' Suzume": 0.16216216216216217,
 'DZ-SS09/013EN-R : Dragon Deity King of Resurgence, Dragveda': 0.14864864864864866,
 'D-PR/559EN : Defensing Roar': 0.14864864864864866,
 'D-PR/445EN : Stealth Dragon, Shikintan': 0.14864864864864866,
 "D-PR/747EN : The Ancient Magus' Bride": 0.13513513513513514,
 'DZ-SS09/020EN : Union the Sky': 0.13513513513513514,
 'DZ-SS09/010EN-R : Stealth Fiend, Shenryi': 0.13513513513513514,
 'DZ-SS09/017EN : Refreshing Wind Dragon, Dinobreeze': 0.13513513513513514,
 'D-PR/414EN : New Horizons, Yumenokessho ROSE': 0.13513513513513514,
 'D-BT07/Re06EN : Burning Flail Dragon': 0.12162162162162163,
 'D-PR/558EN : Defensing Roar': 0.12162162162162163,
 'D-PR/124EN : Elementaria Sanctitude': 0.12162162162162163,
 'DZ-SS09/014EN-R : Rogue Beast, Sunegosuri': 0.12162162162162163,
 'DZ-SS05/033EN : Who Are These Guys...?': 0.12162162162162163,
 'DZ-BT05/SR03EN : Summit Flare Dragon': 0.12162162162162163,
 'DZ-SS09/018EN-R : Stardust Blade': 0.12162162162162163,
 'DZ-BT01/SR03EN : Dragritter, Falhart': 0.12162162162162163,
 'D-SS12/SIR19EN : Burning Flail Dragon': 0.12162162162162163,
 'D-SS01/SP05EN : Blaze Maiden, Zonne': 0.12162162162162163,
 'D-BT01/013EN : Dragon Deity King of Resurgence, Dragveda': 0.10810810810810811,
 'D-BT07/Re01EN : Blaze Maiden, Parama': 0.10810810810810811,
 'D-BT06/016EN : Dragon Deity King of Resurgence, Dragveda': 0.10810810810810811,
 'D-SS01/011EN : Blaze Maiden, Rona': 0.10810810810810811,
 'D-SD01/011EN : Blaze Maiden, Zonne': 0.10810810810810811,
 'D-BT07/Re11EN : Flare Veil Dragon': 0.10810810810810811,
 'DZ-BT01/019EN : Dragon Deity King of Resurgence, Dragveda': 0.10810810810810811,
 'DZ-BT03/EX11EN : Pastel✽Palettes, Aya Maruyama': 0.10810810810810811,
 'DZ-BT12/003EN : Dragonvortex, Belligeacro': 0.10810810810810811,
 'D-PR/002EN : Twin Buckler Dragon': 0.0945945945945946,
 'DZ-BT07/020EN : Dragon Deity King of Resurgence, Dragveda': 0.0945945945945946,
 'D-SS12/SIR20EN : Flare Veil Dragon': 0.0945945945945946,
 'D-PR/442EN : Stealth Dragon, Madowazu': 0.0945945945945946,
 'D-BT02/H05EN : Blaze Maiden, Parama': 0.0945945945945946,
 'D-BT04/SP31EN : Flare Veil Dragon': 0.0945945945945946,
 'D-BT01/063EN : Conduct Spark Dragon': 0.0945945945945946,
 'D-BT06/038EN : Sparkle Rejector Dragon': 0.0945945945945946,
 'DZ-BT02/043EN : Rewrite the Star, Vyrgilla': 0.08108108108108109,
 'DZ-SS04/017EN : Stardust Blade': 0.08108108108108109,
 'DZ-BT01/143EN : Light Elemental, Pachiri': 0.08108108108108109,
 'DZ-BT01/FFR03EN : Dragritter, Falhart': 0.08108108108108109,
 'D-BT02/SP26EN : Blaze Maiden, Parama': 0.08108108108108109,
 'D-PR/516EN : Union the Sky': 0.06756756756756757,
 'DZ-SS09/017EN-R : Refreshing Wind Dragon, Dinobreeze': 0.06756756756756757,
 'D-PR/382EN : Wood Elemental, Leafy': 0.06756756756756757,
 'DZ-SS09/020EN-R : Union the Sky': 0.06756756756756757,
 'D-PR/229EN : Elementaria Sanctitude': 0.06756756756756757,
 'D-BT06/065EN : Blaze War Monk, Sougyou': 0.06756756756756757,
 'D-BT01/SP26EN : Twin Buckler Dragon': 0.06756756756756757,
 'DZ-SS10/021EN : Shiki Otei': 0.06756756756756757,
 'D-PR/577EN : Blaze Maiden, Parama': 0.06756756756756757,
 'DZ-BT08/FFR03EN : Dragritter, Nirmihn': 0.06756756756756757,
 'D-BT05/SP19EN : Stealth Fiend, Amaviera': 0.06756756756756757,
 'D-SS01/SP06EN : Blaze Maiden, Rona': 0.06756756756756757,
 'D-PR/794EN : Bellringer Angel': 0.06756756756756757,
 'D-SD06/010EN : Conduct Spark Dragon': 0.06756756756756757,
 'D-SS05/Re03EN : Twin Buckler Dragon': 0.05405405405405406,
 'D-PR/288EN : Yumenokessho POPY': 0.05405405405405406,
 'D-SS02/015EN : Cure Flare Dracokid': 0.05405405405405406,
 'D-BT01/H10EN : White Light Dragon, Parasolace': 0.05405405405405406,
 'D-PR/741EN : Yumenokessho PASTEL': 0.05405405405405406,
 'D-PR/802EN : Having Fun at Round1, Akina Myodo': 0.05405405405405406,
 "D-PR/748EN : The Ancient Magus' Bride": 0.05405405405405406,
 'DZ-SS01/031EN : Refreshing Wind Dragon, Dinobreeze': 0.05405405405405406,
 'D-BT01/066EN : White Light Dragon, Parasolace': 0.05405405405405406,
 'D-BT11/EX26EN : Morfonica, Mashiro Kurata': 0.05405405405405406,
 'D-SS05/033EN : Stealth Dragon, Madowazu': 0.05405405405405406,
 'D-PR/090EN : Burning Flail Dragon ': 0.05405405405405406,
 'D-PR/795EN : Lyrial, Archer Throne': 0.05405405405405406,
 'D-BT11/EX10EN : Afterglow, Tsugumi Hazawa': 0.04054054054054054,
 'DZ-BT09/003EN : Battle Monk of Water Scales, Ryuutou': 0.04054054054054054,
 'D-PR/729EN : Stealth Dragon, Utsuroi': 0.04054054054054054,
 'D-PR/730EN : Stealth Dragon, Utsuroi': 0.04054054054054054,
 'D-BT01/H07EN : Conduct Spark Dragon': 0.04054054054054054,
 'D-BT01/H03EN : Twin Buckler Dragon': 0.04054054054054054,
 'D-BT06/FR06EN : Sparkle Rejector Dragon': 0.04054054054054054,
 'D-SS09/012EN : Dragon Deity King of Resurgence, Dragveda': 0.04054054054054054,
 'DZ-BT03/045EN : Flare Veil Dragon': 0.04054054054054054,
 'DZ-SS06/020EN : Elementaria Sanctitude': 0.04054054054054054,
 'D-BT12/003EN : Red Jeweled Beast, Galnet': 0.04054054054054054,
 'DZ-SS08/035EN : Blaze Maiden, Reony': 0.04054054054054054,
 'DZ-BT03/EX16EN : Roselia, Yukina Minato': 0.04054054054054054,
 'D-BT11/EX13EN : Pastel✽Palettes, Chisato Shirasagi': 0.02702702702702703,
 'D-PR/352EN : Elementaria Sanctitude': 0.02702702702702703,
 'DZ-SS01/015EN : Flame Leaf Chaotic Dance, Hakusui&amp;Remred': 0.02702702702702703,
 'D-PR/576EN : Flare Veil Dragon': 0.02702702702702703,
 'DZ-BT05/FFR03EN : Summit Flare Dragon': 0.02702702702702703,
 'DZ-BT03/EX38EN : MyGO!!!!! Rana Kaname': 0.02702702702702703,
 'DZ-BT03/EX40EN : MyGO!!!!! Taki Shiina': 0.02702702702702703,
 "D-BT11/EX02EN : Poppin'Party, Tae Hanazono": 0.02702702702702703,
 'D-BT11/EX11EN : Pastel✽Palettes, Aya Maruyama': 0.02702702702702703,
 'DZ-SS09/021EN : Zero Tendo': 0.02702702702702703,
 'DZ-SS10/020EN-R : Protection: Twincast': 0.02702702702702703,
 'DZ-PS01/017EN : Elementaria Sanctitude': 0.02702702702702703,
 'D-PR/356EN : Flare Veil Dragon': 0.02702702702702703,
 'D-BT07/002EN : Meteor Flare Dragon': 0.02702702702702703,
 'D-BT11/EX12EN : Pastel✽Palettes, Hina Hikawa': 0.02702702702702703,
 'D-BT11/EX14EN : Pastel✽Palettes, Maya Yamato': 0.02702702702702703,
 'D-BT11/EX17EN : Roselia, Sayo Hikawa': 0.02702702702702703,
 'D-BT11/EX20EN : Roselia, Rinko Shirokane': 0.02702702702702703,
 'D-BT11/EX23EN : Hello, Happy World! Hagumi Kitazawa': 0.02702702702702703,
 'D-BT11/EX32EN : RAISE A SUILEN, LOCK': 0.02702702702702703,
 'DZ-PS02/017EN : Elementaria Sanctitude': 0.02702702702702703,
 'D-BT11/EX20EN-S : Roselia, Rinko Shirokane': 0.02702702702702703,
 'DZ-BT12/SR03EN : Dragonvortex, Belligeacro': 0.02702702702702703,
 'DZ-BT03/EX19EN : Roselia, Ako Udagawa': 0.013513513513513514,
 'D-BT11/EX31EN : RAISE A SUILEN, LAYER': 0.013513513513513514,
 'D-BT11/EX33EN : RAISE A SUILEN, MASKING': 0.013513513513513514,
 'D-BT11/EX35EN : RAISE A SUILEN, CHU²': 0.013513513513513514,
 'DZ-BT03/EX15EN : Pastel✽Palettes, Eve Wakamiya': 0.013513513513513514,
 'DZ-BT03/EX17EN : Roselia, Sayo Hikawa': 0.013513513513513514,
 'D-PR/578EN : Elementaria Sanctitude': 0.013513513513513514,
 'DZ-BT03/EX08EN : Afterglow, Himari Uehara': 0.013513513513513514,
 'DZ-BT03/EX14EN : Pastel✽Palettes, Maya Yamato': 0.013513513513513514,
 'DZ-BT03/EX27EN : Morfonica, Toko Kirigaya': 0.013513513513513514,
 'DZ-BT03/EX39EN : MyGO!!!!! Soyo Nagasaki': 0.013513513513513514,
 'D-PR/466EN : Divinez, Nao Inabe': 0.013513513513513514,
 'DZ-BT03/EX16EN-S : Roselia, Yukina Minato': 0.013513513513513514,
 'DZ-BT03/EX17EN-S : Roselia, Sayo Hikawa': 0.013513513513513514,
 'DZ-BT03/EX18EN-S : Roselia, Lisa Imai': 0.013513513513513514,
 'DZ-BT03/EX19EN-S : Roselia, Ako Udagawa': 0.013513513513513514,
 'DZ-BT03/EX20EN-S : Roselia, Rinko Shirokane': 0.013513513513513514,
 'DZ-BT03/EX32EN-S : RAISE A SUILEN, LOCK': 0.013513513513513514,
 'DZ-BT03/EX36EN-S : MyGO!!!!! Tomori Takamatsu': 0.013513513513513514,
 'D-SS05/004EN : Evergreen Transphere': 0.013513513513513514,
 'D-PR/501EN : will+Dress Season2, Yu-yu Kondo': 0.013513513513513514,
 'D-PR/503EN : overDress, Yu-yu Kondo': 0.013513513513513514,
 "DZ-BT03/EX03EN : Poppin'Party, Rimi Ushigome": 0.013513513513513514,
 'DZ-BT03/EX06EN : Afterglow, Ran Mitake': 0.013513513513513514,
 'DZ-BT03/EX12EN : Pastel✽Palettes, Hina Hikawa': 0.013513513513513514,
 'DZ-BT03/EX23EN : Hello, Happy World! Hagumi Kitazawa': 0.013513513513513514,
 'D-SS02/SP11EN : Cure Flare Dracokid': 0.013513513513513514,
 "D-BT11/EX02EN-S : Poppin'Party, Tae Hanazono": 0.013513513513513514,
 'D-BT11/EX27EN-S : Morfonica, Toko Kirigaya': 0.013513513513513514,
 'D-BT11/EX28EN-S : Morfonica, Nanami Hiromachi': 0.013513513513513514,
 'D-BT11/EX29EN-S : Morfonica, Tsukushi Futaba': 0.013513513513513514,
 'D-BT11/EX30EN-S : Morfonica, Rui Yashio': 0.013513513513513514,
 'D-PR/824EN : Rogue Beast, Sunegosuri': 0.013513513513513514,
 "DZ-SS05/GCR02EN : 'Butto Bird' Suzume": 0.013513513513513514,
 'D-BT12/FFR03EN : Red Jeweled Beast, Galnet': 0.013513513513513514,
 'DZ-BT03/EX10EN : Afterglow, Tsugumi Hazawa': 0.013513513513513514,
 'DZ-BT03/EX29EN : Morfonica, Tsukushi Futaba': 0.013513513513513514,
 "D-BT11/EX04EN : Poppin'Party, Saya Yamabuki": 0.013513513513513514,
 'D-BT11/EX19EN : Roselia, Ako Udagawa': 0.013513513513513514,
 'D-BT11/EX34EN : RAISE A SUILEN, PAREO': 0.013513513513513514,
 'D-PR/742EN : Yumenokessho HALO': 0.013513513513513514,
 'DZ-SS01/Re04EN : Cure Flare Dracokid': 0.013513513513513514,
 'D-PR/354EN : Blaze Maiden, Parama': 0.013513513513513514,
 'DZ-BT03/EX26EN-S : Morfonica, Mashiro Kurata': 0.013513513513513514,
 'DZ-BT03/EX36EN : MyGO!!!!! Tomori Takamatsu': 0.013513513513513514,
 'DZ-BT03/EX37EN : MyGO!!!!! Anon Chihaya': 0.013513513513513514,
 'DZ-BT03/EX39EN-S : MyGO!!!!! Soyo Nagasaki': 0.013513513513513514,
 'DZ-BT03/EX22EN : Hello, Happy World! Kaoru Seta': 0.013513513513513514,
 'DZ-BT03/EX25EN : Hello, Happy World! Michelle': 0.013513513513513514,
 'DZ-BT03/EX33EN : RAISE A SUILEN, MASKING': 0.013513513513513514,
 'DZ-BT06/020EN : Fire Regalis': 0.013513513513513514,
 "DZ-SS05/CR30EN : 'Usotsuki! Gokuoh-kun' Gokuoh": 0.013513513513513514,
 'DZ-BT03/EX14EN-S : Pastel✽Palettes, Maya Yamato': 0.013513513513513514,
 'D-BT11/EX13EN-S : Pastel✽Palettes, Chisato Shirasagi': 0.013513513513513514,
 'D-BT11/EX15EN-S : Pastel✽Palettes, Eve Wakamiya': 0.013513513513513514,
 'D-BT11/EX16EN-S : Roselia, Yukina Minato': 0.013513513513513514,
 'D-BT11/EX25EN-S : Hello, Happy World! Michelle': 0.013513513513513514,
 'D-BT11/EX34EN-S : RAISE A SUILEN, PAREO': 0.013513513513513514,
 'DZ-BT12/EX41EN : 10th anniv Ave Mujica, Doloris': 0.013513513513513514,
 'DZ-BT12/EX43EN : 10th anniv Ave Mujica, Timoris': 0.013513513513513514,
 'DZ-BT12/EX45EN : 10th anniv Ave Mujica, Oblivionis': 0.013513513513513514,
 'DZ-BT12/EX55EN : Ave Mujica, Oblivionis': 0.013513513513513514,
 'DZ-BT03/EX28EN-S : Morfonica, Nanami Hiromachi': 0.013513513513513514,
 'DZ-BT03/EX29EN-S : Morfonica, Tsukushi Futaba': 0.013513513513513514,
 'DZ-BT03/EX38EN-S : MyGO!!!!! Rana Kaname': 0.013513513513513514}

In [ ]:
bot_dict

{"DZ-SS08/007EN : Vyrgilla, 'Rewrite Form: Alfknights'": 3.6973684210526314,
 'DZ-BT08/003EN : Dragritter, Nirmihn': 3.206140350877193,
 'DZ-SS04/006EN : Ezerwur': 1.868421052631579,
 'D-PR/333EN : Stealth Fiend, Shenryi': 1.7236842105263157,
 'DZ-SS09/011EN : Flare Cosmor': 1.4846491228070176,
 'DZ-SS09/007EN : Ezerwur': 1.3771929824561404,
 'D-PR/725EN : Variance Ray Dragon': 1.0153508771929824,
 'DZ-SS04/011EN : Twin Buckler Dragon': 0.9890350877192983,
 'DZ-SS04/005EN : Flag-raising of Courage, Fanvare': 0.8267543859649122,
 'DZ-SS01/Re05EN : Stealth Fiend, Amaviera': 0.7960526315789473,
 'D-BT05/022EN : Stealth Fiend, Amaviera': 0.7719298245614035,
 'DZ-SS09/010EN : Stealth Fiend, Shenryi': 0.7675438596491229,
 'DZ-SS09/001EN-R : Rewrite the Star, Vyrgilla': 0.7368421052631579,
 'DZ-SS09/014EN : Rogue Beast, Sunegosuri': 0.7171052631578947,
 'DZ-SS09/019EN : Blazing Star Cross': 0.6842105263157895,
 'DZ-SS09/006EN : Flag-raising of Courage, Fanvare': 0.6776315789473685,
 'DZ-SS01/Re37EN : Stealth Fiend, Shenryi': 0.668859649122807,
 'DZ-SS08/001EN : Dragritter, Miqdard': 0.6557017543859649,
 'DZ-SS04/013EN : Rogue Beast, Sunegosuri': 0.6271929824561403,
 'D-BT11/065EN : Defensing Roar': 0.6162280701754386,
 'DZ-SS09/009EN : Opening of the End, Enwing': 0.5767543859649122,
 'D-BT02/030EN : Blaze Maiden, Parama': 0.5416666666666666,
 'DZ-SS09/001EN : Rewrite the Star, Vyrgilla': 0.5175438596491229,
 'DZ-SS09/007EN-R : Ezerwur': 0.4868421052631579,
 'DZ-SS04/017EN-R : Stardust Blade': 0.45394736842105265,
 'D-BT04/034EN : Flare Veil Dragon': 0.45394736842105265,
 'DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla': 0.4517543859649123,
 'DZ-BT01/003EN : Dragritter, Falhart': 0.44956140350877194,
 'DZ-BT03/043EN : Protection: Twincast': 0.4342105263157895,
 'DZ-BT05/003EN : Summit Flare Dragon': 0.4232456140350877,
 'DZ-BT03/046EN : Blaze Maiden, Parama': 0.4166666666666667,
 'D-BT03/030EN : Burning Flail Dragon': 0.4144736842105263,
 'DZ-BT08/SR03EN : Dragritter, Nirmihn': 0.3881578947368421,
 'DZ-SS09/006EN-R : Flag-raising of Courage, Fanvare': 0.38596491228070173,
 'DZ-SS04/016EN : Refreshing Wind Dragon, Dinobreeze': 0.38377192982456143,
 'D-SD01/011EN : Blaze Maiden, Zonne': 0.36622807017543857,
 'DZ-SS04/001EN : Rewrite the Star, Vyrgilla': 0.34649122807017546,
 'DZ-SS09/011EN-R : Flare Cosmor': 0.33114035087719296,
 'DZ-SS09/019EN-R : Blazing Star Cross': 0.32894736842105265,
 'DZ-SS08/032EN : Blaze War Monk, Sougyou': 0.3157894736842105,
 'DZ-SS09/017EN : Refreshing Wind Dragon, Dinobreeze': 0.3092105263157895,
 'DZ-BT07/070EN : Guardian Monk of Raging Flames, Monju': 0.30701754385964913,
 'DZ-BT01/054EN : Guardian Monk of Raging Flames, Monju': 0.29605263157894735,
 'DZ-BT02/FR05EN : Rewrite the Star, Vyrgilla': 0.27631578947368424,
 'DZ-SS09/018EN-R : Stardust Blade': 0.2719298245614035,
 'DZ-BT07/056EN : Flare Veil Dragon': 0.2675438596491228,
 'DZ-SS04/006EN-R : Ezerwur': 0.2631578947368421,
 'DZ-SS09/021EN : Zero Tendo': 0.2631578947368421,
 'DZ-BT03/044EN : Burning Flail Dragon': 0.25877192982456143,
 'D-PR/726EN : Variance Ray Dragon': 0.24780701754385964,
 'D-SS12/093EN : Blaze Maiden, Parama': 0.23903508771929824,
 'DZ-SS09/018EN : Stardust Blade': 0.23464912280701755,
 'DZ-SS09/010EN-R : Stealth Fiend, Shenryi': 0.23026315789473684,
 'DZ-SS08/035EN : Blaze Maiden, Reony': 0.2236842105263158,
 "DZ-SS08/FFR01EN : Vyrgilla, 'Rewrite Form: Alfknights'": 0.21710526315789475,
 'D-SS01/008EN : Blaze Maiden, Zonne': 0.2149122807017544,
 'D-BT01/031EN : Twin Buckler Dragon': 0.21052631578947367,
 'DZ-SS09/009EN-R : Opening of the End, Enwing': 0.20833333333333334,
 'DZ-SS04/005EN-R : Flag-raising of Courage, Fanvare': 0.20394736842105263,
 'DZ-BT07/055EN : Burning Flail Dragon': 0.19298245614035087,
 'DZ-BT01/FR08EN : Guardian Monk of Raging Flames, Monju': 0.19078947368421054,
 'D-SD01/014EN : Blaze Maiden, Rona': 0.19078947368421054,
 'D-SS09/008EN-R : Stealth Dragon, Utsuroi': 0.18421052631578946,
 'D-PR/WO01EN : Stealth Fiend, Souko': 0.18421052631578946,
 'D-BT06/065EN : Blaze War Monk, Sougyou': 0.18201754385964913,
 'D-SS05/Re04EN : Blaze Maiden, Parama': 0.17982456140350878,
 'D-SS09/013EN : Stealth Dragon, Madowazu': 0.17543859649122806,
 'D-PR/559EN : Defensing Roar': 0.17324561403508773,
 'D-BT01/013EN : Dragon Deity King of Resurgence, Dragveda': 0.17105263157894737,
 'DZ-SS09/013EN : Dragon Deity King of Resurgence, Dragveda': 0.16447368421052633,
 'D-PR/558EN : Defensing Roar': 0.16447368421052633,
 'DZ-SS09/014EN-R : Rogue Beast, Sunegosuri': 0.16228070175438597,
 'DZ-SS10/020EN : Protection: Twincast': 0.15789473684210525,
 'DZ-BT07/152EN : Light Elemental, Pachiri': 0.15789473684210525,
 'D-BT02/H05EN : Blaze Maiden, Parama': 0.15570175438596492,
 'DZ-SS09/013EN-R : Dragon Deity King of Resurgence, Dragveda': 0.15570175438596492,
 'D-PR/803EN : Having Fun at Round1, Nao Inabe': 0.15570175438596492,
 'D-BT01/SP13EN : Dragon Deity King of Resurgence, Dragveda': 0.15350877192982457,
 'D-SS05/Re03EN : Twin Buckler Dragon': 0.15350877192982457,
 'D-BT06/038EN : Sparkle Rejector Dragon': 0.15350877192982457,
 'DZ-BT03/045EN : Flare Veil Dragon': 0.14912280701754385,
 'D-PR/289EN : Yumenokessho ROSE': 0.14473684210526316,
 'DZ-SS04/017EN : Stardust Blade': 0.14035087719298245,
 'DZ-BT08/FFR03EN : Dragritter, Nirmihn': 0.13815789473684212,
 'D-SS05/033EN : Stealth Dragon, Madowazu': 0.13596491228070176,
 'DZ-BT07/020EN : Dragon Deity King of Resurgence, Dragveda': 0.1337719298245614,
 'DZ-SS09/020EN : Union the Sky': 0.12719298245614036,
 'D-SS05/Re05EN : Burning Flail Dragon': 0.125,
 'D-BT01/063EN : Conduct Spark Dragon': 0.12280701754385964,
 'D-BT01/H07EN : Conduct Spark Dragon': 0.12280701754385964,
 'DZ-BT12/003EN : Dragonvortex, Belligeacro': 0.12280701754385964,
 'D-PR/002EN : Twin Buckler Dragon': 0.1206140350877193,
 'D-BT01/SP26EN : Twin Buckler Dragon': 0.11842105263157894,
 'D-PR/516EN : Union the Sky': 0.11842105263157894,
 'D-SS12/091EN : Burning Flail Dragon': 0.11842105263157894,
 'DZ-SS01/028EN : Rogue Beast, Sunegosuri': 0.1162280701754386,
 'D-PR/124EN : Elementaria Sanctitude': 0.1162280701754386,
 'D-BT02/SP26EN : Blaze Maiden, Parama': 0.1162280701754386,
 'D-SS01/011EN : Blaze Maiden, Rona': 0.1162280701754386,
 'DZ-SS05/098EN : Nusa~~': 0.1162280701754386,
 'D-SS09/008EN : Stealth Dragon, Utsuroi': 0.11403508771929824,
 "D-PR/747EN : The Ancient Magus' Bride": 0.11403508771929824,
 'D-BT06/068EN : Blaze Maiden, Reony': 0.1074561403508772,
 'BCS2526/VGS01 : Guardian Monk of Raging Flames, Monju': 0.1074561403508772,
 'D-BT06/FR06EN : Sparkle Rejector Dragon': 0.10526315789473684,
 'DZ-BT05/SR03EN : Summit Flare Dragon': 0.10307017543859649,
 'D-SS01/SP05EN : Blaze Maiden, Zonne': 0.10307017543859649,
 'D-SS12/092EN : Flare Veil Dragon': 0.10087719298245613,
 'D-SS12/SIR18EN : Blaze Maiden, Parama': 0.09868421052631579,
 'DZ-SS05/034EN : Cold Noodles Are Gone': 0.09649122807017543,
 'D-BT01/H03EN : Twin Buckler Dragon': 0.09649122807017543,
 'DZ-BT02/043EN : Rewrite the Star, Vyrgilla': 0.09429824561403509,
 'D-SS05/Re06EN : Flare Veil Dragon': 0.09429824561403509,
 'D-SD06/010EN : Conduct Spark Dragon': 0.09429824561403509,
 'DZ-SS09/017EN-R : Refreshing Wind Dragon, Dinobreeze': 0.08991228070175439,
 'DZ-BT01/019EN : Dragon Deity King of Resurgence, Dragveda': 0.08991228070175439,
 'D-PR/413EN : New Horizons, Yumenokessho POPY': 0.08991228070175439,
 'DZ-SS05/037EN : Are You Trying To Kill Me~~~~!!!!': 0.08991228070175439,
 'D-PR/577EN : Blaze Maiden, Parama': 0.08991228070175439,
 'D-SS12/SIR19EN : Burning Flail Dragon': 0.08771929824561403,
 'D-SS09/016EN : Stealth Dragon, Shikintan': 0.08771929824561403,
 'D-BT07/Re11EN : Flare Veil Dragon': 0.08552631578947369,
 'D-BT06/016EN : Dragon Deity King of Resurgence, Dragveda': 0.08333333333333333,
 'D-BT07/Re01EN : Blaze Maiden, Parama': 0.08114035087719298,
 'D-PR/742EN : Yumenokessho HALO': 0.08114035087719298,
 "DZ-SS05/CR02EN : 'Butto Bird' Suzume": 0.08114035087719298,
 'D-BT03/SP36EN : Burning Flail Dragon': 0.07894736842105263,
 'D-BT04/SP31EN : Flare Veil Dragon': 0.07675438596491228,
 'D-PR/795EN : Lyrial, Archer Throne': 0.07675438596491228,
 'DZ-BT09/003EN : Battle Monk of Water Scales, Ryuutou': 0.07456140350877193,
 'D-BT01/H10EN : White Light Dragon, Parasolace': 0.07456140350877193,
 'D-PR/229EN : Elementaria Sanctitude': 0.07017543859649122,
 'D-PR/794EN : Bellringer Angel': 0.07017543859649122,
 'DZ-SS05/033EN : Who Are These Guys...?': 0.06578947368421052,
 'DZ-SS09/020EN-R : Union the Sky': 0.06359649122807018,
 'D-SS12/SIR20EN : Flare Veil Dragon': 0.06359649122807018,
 'D-BT05/SP19EN : Stealth Fiend, Amaviera': 0.06140350877192982,
 'D-PR/382EN : Wood Elemental, Leafy': 0.05921052631578947,
 'D-PR/575EN : Burning Flail Dragon': 0.05921052631578947,
 'DZ-SS10/020EN-R : Protection: Twincast': 0.05701754385964912,
 'DZ-BT01/SR03EN : Dragritter, Falhart': 0.05482456140350877,
 'D-PR/288EN : Yumenokessho POPY': 0.05482456140350877,
 'DZ-SS04/009EN : Cosmor': 0.05482456140350877,
 'DZ-SS04/007EN : Inductance Dragon': 0.05482456140350877,
 'DZ-SS06/020EN : Elementaria Sanctitude': 0.05263157894736842,
 'D-PR/802EN : Having Fun at Round1, Akina Myodo': 0.05263157894736842,
 'DZ-BT01/143EN : Light Elemental, Pachiri': 0.05263157894736842,
 'D-PR/414EN : New Horizons, Yumenokessho ROSE': 0.05263157894736842,
 'D-PR/729EN : Stealth Dragon, Utsuroi': 0.05263157894736842,
 'D-SS05/036EN : Stealth Dragon, Shikintan': 0.05043859649122807,
 'D-PR/741EN : Yumenokessho PASTEL': 0.05043859649122807,
 'DZ-SS04/015EN : Electrake Dracokid': 0.04824561403508772,
 'D-PR/352EN : Elementaria Sanctitude': 0.046052631578947366,
 'D-PR/354EN : Blaze Maiden, Parama': 0.046052631578947366,
 'DZ-SS01/015EN : Flame Leaf Chaotic Dance, Hakusui&amp;Remred': 0.046052631578947366,
 'D-SS01/SP06EN : Blaze Maiden, Rona': 0.046052631578947366,
 'DZ-BT01/FFR03EN : Dragritter, Falhart': 0.043859649122807015,
 'D-PR/442EN : Stealth Dragon, Madowazu': 0.043859649122807015,
 'DZ-SS01/031EN : Refreshing Wind Dragon, Dinobreeze': 0.041666666666666664,
 'D-SS02/015EN : Cure Flare Dracokid': 0.041666666666666664,
 'D-PR/576EN : Flare Veil Dragon': 0.041666666666666664,
 'DZ-SS01/Re04EN : Cure Flare Dracokid': 0.041666666666666664,
 'DZ-SS10/021EN : Shiki Otei': 0.039473684210526314,
 'D-BT01/066EN : White Light Dragon, Parasolace': 0.039473684210526314,
 'D-BT07/Re06EN : Burning Flail Dragon': 0.039473684210526314,
 'DZ-SS04/010EN : Dragritter, Jabre': 0.039473684210526314,
 'D-SS09/012EN : Dragon Deity King of Resurgence, Dragveda': 0.03728070175438596,
 'DZ-BT05/FFR03EN : Summit Flare Dragon': 0.03728070175438596,
 'D-PR/445EN : Stealth Dragon, Shikintan': 0.03728070175438596,
 'DZ-SS04/014EN : Jaggy Dagger Dragon': 0.03728070175438596,
 'D-PR/503EN : overDress, Yu-yu Kondo': 0.03289473684210526,
 'D-PR/356EN : Flare Veil Dragon': 0.03070175438596491,
 'DZ-TD01/017EN : Refreshing Wind Dragon, Dinobreeze': 0.03070175438596491,
 'DZ-SS04/008EN : Djinn of Trusting Luck': 0.03070175438596491,
 'DZ-TD01/014EN : Rogue Beast, Sunegosuri': 0.03070175438596491,
 'D-SD06/013EN : White Light Dragon, Parasolace': 0.02850877192982456,
 'D-PR/355EN : Burning Flail Dragon': 0.02631578947368421,
 'D-BT07/002EN : Meteor Flare Dragon': 0.02631578947368421,
 'DZ-BT01/146EN : Wood Elemental, Leafy': 0.02631578947368421,
 'D-PR/824EN : Rogue Beast, Sunegosuri': 0.02631578947368421,
 'D-BT11/EX16EN-S : Roselia, Yukina Minato': 0.02412280701754386,
 'D-PR/090EN : Burning Flail Dragon ': 0.02412280701754386,
 'DZ-BT06/020EN : Fire Regalis': 0.02412280701754386,
 'D-BT12/003EN : Red Jeweled Beast, Galnet': 0.02412280701754386,
 'DZ-SS08/019EN : Flame Leaf Chaotic Dance, Hakusui&amp;Remred': 0.02412280701754386,
 'DZ-BT07/155EN : Wood Elemental, Leafy': 0.021929824561403508,
 'D-BT11/EX32EN-S : RAISE A SUILEN, LOCK': 0.021929824561403508,
 'D-BT11/EX20EN-S : Roselia, Rinko Shirokane': 0.021929824561403508,
 'DZ-BT03/EX06EN-S : Afterglow, Ran Mitake': 0.021929824561403508,
 'D-PR/381EN : Light Elemental, Pachiri': 0.021929824561403508,
 'DZ-BT03/EX21EN : Hello, Happy World! Kokoro Tsurumaki': 0.021929824561403508,
 'D-PR/466EN : Divinez, Nao Inabe': 0.019736842105263157,
 'DZ-SS09/012EN : Escort Stealth Dragon, Hayashi Kaze': 0.019736842105263157,
 'DZ-BT12/FFR03EN : Dragonvortex, Belligeacro': 0.019736842105263157,
 'DZ-SS09/016EN : Electrake Dracokid': 0.017543859649122806,
 'DZ-BT03/EX15EN-S : Pastel✽Palettes, Eve Wakamiya': 0.017543859649122806,
 'DZ-BT03/EX37EN : MyGO!!!!! Anon Chihaya': 0.017543859649122806,
 'DZ-BT09/SR03EN : Battle Monk of Water Scales, Ryuutou': 0.017543859649122806,
 'D-BT13/020EN : Great Scale Supporter, Rovania': 0.017543859649122806,
 'DZ-BT06/024EN : Stealth Fiend, Futakuchiyo': 0.017543859649122806,
 'D-BT11/EX34EN-S : RAISE A SUILEN, PAREO': 0.017543859649122806,
 'D-PR/353EN : Guardian Monk of Raging Flames, Monju': 0.017543859649122806,
 'DZ-BT02/077EN : Stardust Blade': 0.015350877192982455,
 'DZ-PS02/017EN : Elementaria Sanctitude': 0.015350877192982455,
 'DZ-BT03/EX22EN-S : Hello, Happy World! Kaoru Seta': 0.015350877192982455,
 'D-PR/730EN : Stealth Dragon, Utsuroi': 0.015350877192982455,
 'DZ-PS01/017EN : Elementaria Sanctitude': 0.015350877192982455,
 'DZ-BT03/EX33EN : RAISE A SUILEN, MASKING': 0.015350877192982455,
 'DZ-BT03/EX32EN : RAISE A SUILEN, LOCK': 0.015350877192982455,
 'DZ-SS09/008EN : Inductance Dragon': 0.015350877192982455,
 'DZ-BT03/EX23EN : Hello, Happy World! Hagumi Kitazawa': 0.015350877192982455,
 'D-BT11/EX31EN : RAISE A SUILEN, LAYER': 0.013157894736842105,
 'D-BT02/067EN : Flame Dragon Bombardment': 0.013157894736842105,
 'D-BT11/EX09EN-S : Afterglow, Tomoe Udagawa': 0.013157894736842105,
 'DZ-BT03/EX40EN-S : MyGO!!!!! Taki Shiina': 0.013157894736842105,
 'D-BT11/003EN : Dragritter, Lateefa': 0.013157894736842105,
 "DZ-BT03/EX03EN : Poppin'Party, Rimi Ushigome": 0.013157894736842105,
 "DZ-BT03/EX05EN : Poppin'Party, Arisa Ichigaya": 0.013157894736842105,
 'DZ-BT03/EX20EN : Roselia, Rinko Shirokane': 0.013157894736842105,
 'DZ-BT03/EX39EN : MyGO!!!!! Soyo Nagasaki': 0.013157894736842105,
 'DZ-BT03/EX38EN : MyGO!!!!! Rana Kaname': 0.013157894736842105,
 'DZ-BT03/EX09EN : Afterglow, Tomoe Udagawa': 0.013157894736842105,
 "DZ-SS05/CR30EN : 'Usotsuki! Gokuoh-kun' Gokuoh": 0.013157894736842105,
 'DZ-BT03/EX25EN-S : Hello, Happy World! Michelle': 0.013157894736842105,
 'DZ-BT03/EX07EN-S : Afterglow, Moca Aoba': 0.013157894736842105,
 'DZ-BT03/EX34EN : RAISE A SUILEN, PAREO': 0.013157894736842105,
 'DZ-BT03/EX35EN : RAISE A SUILEN, CHU²': 0.013157894736842105,
 'D-BT11/EX06EN : Afterglow, Ran Mitake': 0.013157894736842105,
 'DZ-BT03/EX25EN : Hello, Happy World! Michelle': 0.013157894736842105,
 'D-BT11/EX11EN : Pastel✽Palettes, Aya Maruyama': 0.013157894736842105,
 'D-BT11/EX07EN : Afterglow, Moca Aoba': 0.010964912280701754,
 'D-BT11/EX31EN-S : RAISE A SUILEN, LAYER': 0.010964912280701754,
 'D-SS08/023EN : Elementaria Sanctitude': 0.010964912280701754,
 'DZ-BT03/EX11EN-S : Pastel✽Palettes, Aya Maruyama': 0.010964912280701754,
 'DZ-BT03/EX33EN-S : RAISE A SUILEN, MASKING': 0.010964912280701754,
 'DZ-BT03/EX36EN : MyGO!!!!! Tomori Takamatsu': 0.010964912280701754,
 'DZ-BT03/EX40EN : MyGO!!!!! Taki Shiina': 0.010964912280701754,
 'DZ-BT03/EX07EN : Afterglow, Moca Aoba': 0.010964912280701754,
 'DZ-BT03/EX19EN : Roselia, Ako Udagawa': 0.010964912280701754,
 'DZ-BT03/EX21EN-S : Hello, Happy World! Kokoro Tsurumaki': 0.010964912280701754,
 'D-BT07/058EN : Dragritter, Midhat': 0.010964912280701754,
 'DZ-BT03/EX18EN-S : Roselia, Lisa Imai': 0.010964912280701754,
 'DZ-BT03/EX24EN : Hello, Happy World! Kanon Matsubara': 0.010964912280701754,
 'DZ-BT12/SR03EN : Dragonvortex, Belligeacro': 0.010964912280701754,
 'D-BT11/EX33EN : RAISE A SUILEN, MASKING': 0.008771929824561403,
 'D-BT11/EX07EN-S : Afterglow, Moca Aoba': 0.008771929824561403,
 'D-BT11/EX17EN-S : Roselia, Sayo Hikawa': 0.008771929824561403,
 'DZ-BT03/EX36EN-S : MyGO!!!!! Tomori Takamatsu': 0.008771929824561403,
 'DZ-BT03/EX37EN-S : MyGO!!!!! Anon Chihaya': 0.008771929824561403,
 'DZ-BT03/EX38EN-S : MyGO!!!!! Rana Kaname': 0.008771929824561403,
 'DZ-BT03/EX08EN-S : Afterglow, Himari Uehara': 0.008771929824561403,
 'DZ-BT03/EX10EN-S : Afterglow, Tsugumi Hazawa': 0.008771929824561403,
 'DZ-BT03/EX08EN : Afterglow, Himari Uehara': 0.008771929824561403,
 'DZ-BT03/EX11EN : Pastel✽Palettes, Aya Maruyama': 0.008771929824561403,
 "D-BT11/EX04EN : Poppin'Party, Saya Yamabuki": 0.008771929824561403,
 'D-BT11/EX06EN-S : Afterglow, Ran Mitake': 0.008771929824561403,
 'DZ-BT03/EX06EN : Afterglow, Ran Mitake': 0.008771929824561403,
 'DZ-BT03/EX26EN-S : Morfonica, Mashiro Kurata': 0.008771929824561403,
 'DZ-BT03/EX16EN : Roselia, Yukina Minato': 0.008771929824561403,
 'DZ-BT03/EX29EN : Morfonica, Tsukushi Futaba': 0.008771929824561403,
 'D-PR/803EN-S : Having Fun at Round1, Nao Inabe': 0.008771929824561403,
 "D-BT11/EX04EN-S : Poppin'Party, Saya Yamabuki": 0.008771929824561403,
 'DZ-BT03/EX20EN-S : Roselia, Rinko Shirokane': 0.008771929824561403,
 'D-BT11/EX15EN-S : Pastel✽Palettes, Eve Wakamiya': 0.008771929824561403,
 'D-BT11/EX25EN-S : Hello, Happy World! Michelle': 0.008771929824561403,
 "D-BT11/EX01EN-S : Poppin'Party, Kasumi Toyama": 0.006578947368421052,
 'D-BT11/EX10EN-S : Afterglow, Tsugumi Hazawa': 0.006578947368421052,
 'D-BT11/EX26EN-S : Morfonica, Mashiro Kurata': 0.006578947368421052,
 'D-BT11/EX18EN-S : Roselia, Lisa Imai': 0.006578947368421052,
 'D-BT11/EX19EN-S : Roselia, Ako Udagawa': 0.006578947368421052,
 "DZ-BT03/EX02EN-S : Poppin'Party, Tae Hanazono": 0.006578947368421052,
 'DZ-BT03/EX09EN-S : Afterglow, Tomoe Udagawa': 0.006578947368421052,
 'DZ-BT03/EX29EN-S : Morfonica, Tsukushi Futaba': 0.006578947368421052,
 'DZ-BT03/EX17EN : Roselia, Sayo Hikawa': 0.006578947368421052,
 'D-BT09/019EN : Desolate Spark Dragon': 0.006578947368421052,
 'D-BT11/EX25EN : Hello, Happy World! Michelle': 0.006578947368421052,
 "DZ-BT03/EX03EN-S : Poppin'Party, Rimi Ushigome": 0.006578947368421052,
 "DZ-BT03/EX04EN-S : Poppin'Party, Saya Yamabuki": 0.006578947368421052,
 "DZ-BT03/EX05EN-S : Poppin'Party, Arisa Ichigaya": 0.006578947368421052,
 'D-BT08/034EN : Frying Shot Dragon, Crumstego': 0.006578947368421052,
 'D-PR/578EN : Elementaria Sanctitude': 0.006578947368421052,
 "D-BT11/EX05EN : Poppin'Party, Arisa Ichigaya": 0.006578947368421052,
 'D-BT11/EX28EN-S : Morfonica, Nanami Hiromachi': 0.006578947368421052,
 'D-BT11/EX18EN : Roselia, Lisa Imai': 0.006578947368421052,
 'D-BT11/EX23EN : Hello, Happy World! Hagumi Kitazawa': 0.006578947368421052,
 'DZ-TD01/014EN_9 : Rogue Beast, Sunegosuri': 0.006578947368421052,
 'D-SD01/012EN : Blaze Staff Monk, Cho Kuu Sha': 0.006578947368421052,
 'D-BT11/EX14EN-S : Pastel✽Palettes, Maya Yamato': 0.006578947368421052,
 'D-BT11/EX23EN-S : Hello, Happy World! Hagumi Kitazawa': 0.006578947368421052,
 'D-BT11/EX09EN : Afterglow, Tomoe Udagawa': 0.006578947368421052,
 'D-BT11/EX27EN : Morfonica, Toko Kirigaya': 0.006578947368421052,
 'D-BT11/EX08EN : Afterglow, Himari Uehara': 0.006578947368421052,
 'DZ-BT03/EX30EN-S : Morfonica, Rui Yashio': 0.006578947368421052,
 'DZ-SS04/012EN : Spiritual King of Determination, Olbaria': 0.006578947368421052,
 'D-BT11/EX08EN-S : Afterglow, Himari Uehara': 0.006578947368421052,
 "DZ-SS05/GCR02EN : 'Butto Bird' Suzume": 0.006578947368421052,
 'DZ-BT03/EX14EN-S : Pastel✽Palettes, Maya Yamato': 0.006578947368421052,
 'D-BT11/EX13EN-S : Pastel✽Palettes, Chisato Shirasagi': 0.006578947368421052,
 'DZ-BT03/EX22EN : Hello, Happy World! Kaoru Seta': 0.006578947368421052,
 'DZ-BT03/EX28EN : Morfonica, Nanami Hiromachi': 0.006578947368421052,
 'DZ-SS08/034EN : Blaze Maiden, Arush': 0.006578947368421052,
 'DZ-BT03/EX39EN-S : MyGO!!!!! Soyo Nagasaki': 0.0043859649122807015,
 'D-SS05/004EN : Evergreen Transphere': 0.0043859649122807015,
 'D-BT11/EX11EN-S : Pastel✽Palettes, Aya Maruyama': 0.0043859649122807015,

In [ ]:
all_dict

{"DZ-SS08/007EN : Vyrgilla, 'Rewrite Form: Alfknights'": 3.688679245283019,
 'DZ-BT08/003EN : Dragritter, Nirmihn': 3.218867924528302,
 'DZ-SS04/006EN : Ezerwur': 1.8641509433962264,
 'D-PR/333EN : Stealth Fiend, Shenryi': 1.7169811320754718,
 'DZ-SS09/011EN : Flare Cosmor': 1.4641509433962263,
 'DZ-SS09/007EN : Ezerwur': 1.3773584905660377,
 'D-PR/725EN : Variance Ray Dragon': 1.0113207547169811,
 'DZ-SS04/011EN : Twin Buckler Dragon': 0.9528301886792453,
 'DZ-SS01/Re05EN : Stealth Fiend, Amaviera': 0.8358490566037736,
 'DZ-SS04/005EN : Flag-raising of Courage, Fanvare': 0.8264150943396227,
 'D-BT05/022EN : Stealth Fiend, Amaviera': 0.7830188679245284,
 'DZ-SS09/010EN : Stealth Fiend, Shenryi': 0.779245283018868,
 'DZ-SS09/001EN-R : Rewrite the Star, Vyrgilla': 0.7245283018867924,
 'DZ-SS01/Re37EN : Stealth Fiend, Shenryi': 0.690566037735849,
 'DZ-SS09/019EN : Blazing Star Cross': 0.6886792452830188,
 'DZ-SS09/014EN : Rogue Beast, Sunegosuri': 0.6811320754716981,
 'DZ-SS09/006EN : Flag-raising of Courage, Fanvare': 0.6773584905660377,
 'DZ-SS08/001EN : Dragritter, Miqdard': 0.6679245283018868,
 'D-BT11/065EN : Defensing Roar': 0.630188679245283,
 'DZ-SS04/013EN : Rogue Beast, Sunegosuri': 0.5849056603773585,
 'DZ-SS09/009EN : Opening of the End, Enwing': 0.5509433962264151,
 'D-BT02/030EN : Blaze Maiden, Parama': 0.5471698113207547,
 'DZ-SS09/001EN : Rewrite the Star, Vyrgilla': 0.5245283018867924,
 'DZ-SS09/007EN-R : Ezerwur': 0.47735849056603774,
 'DZ-SS04/017EN-R : Stardust Blade': 0.47547169811320755,
 'DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla': 0.45849056603773586,
 'DZ-BT01/003EN : Dragritter, Falhart': 0.4547169811320755,
 'D-BT04/034EN : Flare Veil Dragon': 0.4547169811320755,
 'DZ-BT03/043EN : Protection: Twincast': 0.439622641509434,
 'DZ-BT05/003EN : Summit Flare Dragon': 0.42830188679245285,
 'D-BT03/030EN : Burning Flail Dragon': 0.41509433962264153,
 'DZ-BT03/046EN : Blaze Maiden, Parama': 0.41320754716981134,
 'DZ-BT08/SR03EN : Dragritter, Nirmihn': 0.40943396226415096,
 'DZ-SS09/006EN-R : Flag-raising of Courage, Fanvare': 0.38113207547169814,
 'DZ-SS04/016EN : Refreshing Wind Dragon, Dinobreeze': 0.3584905660377358,
 'DZ-SS04/001EN : Rewrite the Star, Vyrgilla': 0.35471698113207545,
 'DZ-SS09/011EN-R : Flare Cosmor': 0.3320754716981132,
 'D-SD01/011EN : Blaze Maiden, Zonne': 0.330188679245283,
 'DZ-SS09/019EN-R : Blazing Star Cross': 0.32264150943396225,
 'DZ-SS08/032EN : Blaze War Monk, Sougyou': 0.30566037735849055,
 'DZ-BT01/054EN : Guardian Monk of Raging Flames, Monju': 0.3,
 'DZ-BT07/070EN : Guardian Monk of Raging Flames, Monju': 0.2943396226415094,
 'DZ-SS09/017EN : Refreshing Wind Dragon, Dinobreeze': 0.2849056603773585,
 'DZ-SS04/006EN-R : Ezerwur': 0.27735849056603773,
 'DZ-BT02/FR05EN : Rewrite the Star, Vyrgilla': 0.27169811320754716,
 'DZ-BT07/056EN : Flare Veil Dragon': 0.25471698113207547,
 'D-PR/726EN : Variance Ray Dragon': 0.2528301886792453,
 'DZ-BT03/044EN : Burning Flail Dragon': 0.2528301886792453,
 'DZ-SS09/018EN-R : Stardust Blade': 0.2509433962264151,
 'D-SS12/093EN : Blaze Maiden, Parama': 0.2490566037735849,
 'D-SS01/008EN : Blaze Maiden, Zonne': 0.24528301886792453,
 "DZ-SS08/FFR01EN : Vyrgilla, 'Rewrite Form: Alfknights'": 0.23773584905660378,
 'DZ-SS09/018EN : Stardust Blade': 0.2339622641509434,
 'DZ-SS09/021EN : Zero Tendo': 0.23018867924528302,
 'D-SS09/008EN-R : Stealth Dragon, Utsuroi': 0.2188679245283019,
 'DZ-SS09/010EN-R : Stealth Fiend, Shenryi': 0.2169811320754717,
 'DZ-SS09/009EN-R : Opening of the End, Enwing': 0.21320754716981133,
 'D-BT01/031EN : Twin Buckler Dragon': 0.20943396226415095,
 'DZ-SS04/005EN-R : Flag-raising of Courage, Fanvare': 0.2037735849056604,
 'D-SS05/Re04EN : Blaze Maiden, Parama': 0.2018867924528302,
 'DZ-BT07/055EN : Burning Flail Dragon': 0.2,
 'DZ-SS08/035EN : Blaze Maiden, Reony': 0.19811320754716982,
 'D-SS09/013EN : Stealth Dragon, Madowazu': 0.19433962264150945,
 'DZ-BT01/FR08EN : Guardian Monk of Raging Flames, Monju': 0.19056603773584907,
 'D-PR/WO01EN : Stealth Fiend, Souko': 0.19056603773584907,
 'D-SD01/014EN : Blaze Maiden, Rona': 0.18679245283018867,
 'D-PR/559EN : Defensing Roar': 0.16981132075471697,
 'DZ-SS09/013EN : Dragon Deity King of Resurgence, Dragveda': 0.16792452830188678,
 'D-BT06/065EN : Blaze War Monk, Sougyou': 0.1660377358490566,
 'DZ-BT07/152EN : Light Elemental, Pachiri': 0.1660377358490566,
 'DZ-SS10/020EN : Protection: Twincast': 0.1641509433962264,
 'D-PR/803EN : Having Fun at Round1, Nao Inabe': 0.1641509433962264,
 'D-BT01/013EN : Dragon Deity King of Resurgence, Dragveda': 0.16226415094339622,
 'D-BT01/SP13EN : Dragon Deity King of Resurgence, Dragveda': 0.16037735849056603,
 'D-PR/558EN : Defensing Roar': 0.15849056603773584,
 'DZ-SS09/014EN-R : Rogue Beast, Sunegosuri': 0.15660377358490565,
 'DZ-SS09/013EN-R : Dragon Deity King of Resurgence, Dragveda': 0.15471698113207547,
 'D-PR/289EN : Yumenokessho ROSE': 0.15283018867924528,
 'D-BT02/H05EN : Blaze Maiden, Parama': 0.1471698113207547,
 'D-BT06/038EN : Sparkle Rejector Dragon': 0.14528301886792452,
 'D-SS05/Re03EN : Twin Buckler Dragon': 0.13962264150943396,
 'D-SS09/008EN : Stealth Dragon, Utsuroi': 0.13962264150943396,
 'DZ-SS05/098EN : Nusa~~': 0.13773584905660377,
 'D-SS05/Re05EN : Burning Flail Dragon': 0.13773584905660377,
 'DZ-SS01/028EN : Rogue Beast, Sunegosuri': 0.1339622641509434,
 'DZ-BT03/045EN : Flare Veil Dragon': 0.1339622641509434,
 'DZ-SS04/017EN : Stardust Blade': 0.1320754716981132,
 'DZ-SS09/020EN : Union the Sky': 0.12830188679245283,
 'DZ-BT07/020EN : Dragon Deity King of Resurgence, Dragveda': 0.12830188679245283,
 'DZ-BT08/FFR03EN : Dragritter, Nirmihn': 0.12830188679245283,
 'BCS2526/VGS01 : Guardian Monk of Raging Flames, Monju': 0.12452830188679245,
 'D-SS05/033EN : Stealth Dragon, Madowazu': 0.12452830188679245,
 'D-SS05/Re06EN : Flare Veil Dragon': 0.12264150943396226,
 'DZ-BT12/003EN : Dragonvortex, Belligeacro': 0.12075471698113208,
 'D-PR/413EN : New Horizons, Yumenokessho POPY': 0.11886792452830189,
 'D-BT01/063EN : Conduct Spark Dragon': 0.11886792452830189,
 'D-PR/002EN : Twin Buckler Dragon': 0.1169811320754717,
 'D-PR/124EN : Elementaria Sanctitude': 0.1169811320754717,
 "D-PR/747EN : The Ancient Magus' Bride": 0.1169811320754717,
 'D-SS01/011EN : Blaze Maiden, Rona': 0.11509433962264151,
 'D-PR/516EN : Union the Sky': 0.11132075471698114,
 'D-BT01/H07EN : Conduct Spark Dragon': 0.11132075471698114,
 'D-SS12/092EN : Flare Veil Dragon': 0.11132075471698114,
 'D-BT01/SP26EN : Twin Buckler Dragon': 0.11132075471698114,
 'D-BT02/SP26EN : Blaze Maiden, Parama': 0.11132075471698114,
 'DZ-SS05/037EN : Are You Trying To Kill Me~~~~!!!!': 0.10943396226415095,
 'DZ-SS05/034EN : Cold Noodles Are Gone': 0.10943396226415095,
 'D-SS12/SIR18EN : Blaze Maiden, Parama': 0.10943396226415095,
 'D-SS09/016EN : Stealth Dragon, Shikintan': 0.10754716981132076,
 'DZ-BT05/SR03EN : Summit Flare Dragon': 0.10566037735849057,
 'D-SS01/SP05EN : Blaze Maiden, Zonne': 0.10566037735849057,
 'D-SS12/091EN : Burning Flail Dragon': 0.1018867924528302,
 'D-BT06/FR06EN : Sparkle Rejector Dragon': 0.09622641509433963,
 'D-BT03/SP36EN : Burning Flail Dragon': 0.09433962264150944,
 'DZ-BT02/043EN : Rewrite the Star, Vyrgilla': 0.09245283018867924,
 "DZ-SS05/CR02EN : 'Butto Bird' Suzume": 0.09245283018867924,
 'D-SS12/SIR19EN : Burning Flail Dragon': 0.09245283018867924,
 'DZ-BT01/019EN : Dragon Deity King of Resurgence, Dragveda': 0.09245283018867924,
 'D-BT06/068EN : Blaze Maiden, Reony': 0.09245283018867924,
 'D-SD06/010EN : Conduct Spark Dragon': 0.09056603773584905,
 'D-BT01/H03EN : Twin Buckler Dragon': 0.08867924528301886,
 'D-BT07/Re11EN : Flare Veil Dragon': 0.08867924528301886,
 'D-BT06/016EN : Dragon Deity King of Resurgence, Dragveda': 0.08679245283018867,
 'DZ-SS09/017EN-R : Refreshing Wind Dragon, Dinobreeze': 0.08679245283018867,
 'D-PR/577EN : Blaze Maiden, Parama': 0.08679245283018867,
 'D-BT07/Re01EN : Blaze Maiden, Parama': 0.08490566037735849,
 'D-BT04/SP31EN : Flare Veil Dragon': 0.07924528301886792,
 'DZ-SS05/033EN : Who Are These Guys...?': 0.07358490566037736,
 'D-PR/795EN : Lyrial, Archer Throne': 0.07358490566037736,
 'D-BT01/H10EN : White Light Dragon, Parasolace': 0.07169811320754717,
 'D-PR/742EN : Yumenokessho HALO': 0.07169811320754717,
 'DZ-BT09/003EN : Battle Monk of Water Scales, Ryuutou': 0.06981132075471698,
 'D-PR/229EN : Elementaria Sanctitude': 0.06981132075471698,
 'D-PR/794EN : Bellringer Angel': 0.06981132075471698,
 'D-SS12/SIR20EN : Flare Veil Dragon': 0.06792452830188679,
 'DZ-SS09/020EN-R : Union the Sky': 0.06415094339622641,
 'DZ-BT01/SR03EN : Dragritter, Falhart': 0.06415094339622641,
 'D-PR/414EN : New Horizons, Yumenokessho ROSE': 0.06415094339622641,
 'D-BT05/SP19EN : Stealth Fiend, Amaviera': 0.062264150943396226,
 'D-PR/382EN : Wood Elemental, Leafy': 0.06037735849056604,
 'DZ-BT01/143EN : Light Elemental, Pachiri': 0.05660377358490566,
 'D-PR/288EN : Yumenokessho POPY': 0.05471698113207547,
 'D-PR/445EN : Stealth Dragon, Shikintan': 0.052830188679245285,
 'DZ-SS10/020EN-R : Protection: Twincast': 0.052830188679245285,
 'D-PR/802EN : Having Fun at Round1, Akina Myodo': 0.052830188679245285,
 'D-BT07/Re06EN : Burning Flail Dragon': 0.0509433962264151,
 'D-PR/729EN : Stealth Dragon, Utsuroi': 0.0509433962264151,
 'D-PR/442EN : Stealth Dragon, Madowazu': 0.0509433962264151,
 'DZ-SS06/020EN : Elementaria Sanctitude': 0.0509433962264151,
 'D-PR/741EN : Yumenokessho PASTEL': 0.0509433962264151,
 'D-PR/575EN : Burning Flail Dragon': 0.0509433962264151,
 'DZ-BT01/FFR03EN : Dragritter, Falhart': 0.04905660377358491,
 'D-SS01/SP06EN : Blaze Maiden, Rona': 0.04905660377358491,
 'DZ-SS04/009EN : Cosmor': 0.04716981132075472,
 'DZ-SS04/007EN : Inductance Dragon': 0.04716981132075472,
 'D-SS02/015EN : Cure Flare Dracokid': 0.04339622641509434,
 'D-PR/352EN : Elementaria Sanctitude': 0.04339622641509434,
 'DZ-SS01/015EN : Flame Leaf Chaotic Dance, Hakusui&amp;Remred': 0.04339622641509434,
 'DZ-SS10/021EN : Shiki Otei': 0.04339622641509434,
 'DZ-SS01/031EN : Refreshing Wind Dragon, Dinobreeze': 0.04339622641509434,
 'D-SS05/036EN : Stealth Dragon, Shikintan': 0.04339622641509434,
 'D-BT01/066EN : White Light Dragon, Parasolace': 0.04150943396226415,
 'D-PR/354EN : Blaze Maiden, Parama': 0.04150943396226415,
 'DZ-SS04/015EN : Electrake Dracokid': 0.04150943396226415,
 'D-PR/576EN : Flare Veil Dragon': 0.03962264150943396,
 'D-SS09/012EN : Dragon Deity King of Resurgence, Dragveda': 0.03773584905660377,
 'DZ-SS01/Re04EN : Cure Flare Dracokid': 0.03773584905660377,
 'DZ-BT05/FFR03EN : Summit Flare Dragon': 0.035849056603773584,
 'DZ-SS04/010EN : Dragritter, Jabre': 0.033962264150943396,
 'DZ-SS04/014EN : Jaggy Dagger Dragon': 0.03207547169811321,
 'D-PR/503EN : overDress, Yu-yu Kondo': 0.03018867924528302,
 'D-PR/356EN : Flare Veil Dragon': 0.03018867924528302,
 'D-PR/090EN : Burning Flail Dragon ': 0.02830188679245283,
 'D-BT12/003EN : Red Jeweled Beast, Galnet': 0.026415094339622643,
 'D-BT07/002EN : Meteor Flare Dragon': 0.026415094339622643,
 'DZ-TD01/017EN : Refreshing Wind Dragon, Dinobreeze': 0.026415094339622643,
 'DZ-SS04/008EN : Djinn of Trusting Luck': 0.026415094339622643,
 'DZ-TD01/014EN : Rogue Beast, Sunegosuri': 0.026415094339622643,
 'D-PR/824EN : Rogue Beast, Sunegosuri': 0.024528301886792454,
 'D-SD06/013EN : White Light Dragon, Parasolace': 0.024528301886792454,
 'DZ-BT03/EX11EN : Pastel✽Palettes, Aya Maruyama': 0.022641509433962263,
 'DZ-BT06/020EN : Fire Regalis': 0.022641509433962263,
 'D-BT11/EX16EN-S : Roselia, Yukina Minato': 0.022641509433962263,
 'D-BT11/EX20EN-S : Roselia, Rinko Shirokane': 0.022641509433962263,
 'D-PR/355EN : Burning Flail Dragon': 0.022641509433962263,
 'DZ-BT01/146EN : Wood Elemental, Leafy': 0.022641509433962263,
 'DZ-SS08/019EN : Flame Leaf Chaotic Dance, Hakusui&amp;Remred': 0.020754716981132074,
 'D-PR/730EN : Stealth Dragon, Utsuroi': 0.018867924528301886,
 'D-PR/466EN : Divinez, Nao Inabe': 0.018867924528301886,
 'DZ-BT07/155EN : Wood Elemental, Leafy': 0.018867924528301886,
 'D-BT11/EX32EN-S : RAISE A SUILEN, LOCK': 0.018867924528301886,
 'DZ-BT03/EX06EN-S : Afterglow, Ran Mitake': 0.018867924528301886,
 'D-PR/381EN : Light Elemental, Pachiri': 0.018867924528301886,
 'DZ-BT03/EX21EN : Hello, Happy World! Kokoro Tsurumaki': 0.018867924528301886,
 'DZ-PS01/017EN : Elementaria Sanctitude': 0.016981132075471698,
 'DZ-PS02/017EN : Elementaria Sanctitude': 0.016981132075471698,
 'DZ-BT03/EX37EN : MyGO!!!!! Anon Chihaya': 0.016981132075471698,
 'D-BT11/EX34EN-S : RAISE A SUILEN, PAREO': 0.016981132075471698,
 'DZ-SS09/012EN : Escort Stealth Dragon, Hayashi Kaze': 0.016981132075471698,
 'DZ-BT12/FFR03EN : Dragonvortex, Belligeacro': 0.016981132075471698,
 'DZ-BT03/EX38EN : MyGO!!!!! Rana Kaname': 0.01509433962264151,
 'D-BT11/EX11EN : Pastel✽Palettes, Aya Maruyama': 0.01509433962264151,
 'DZ-BT03/EX23EN : Hello, Happy World! Hagumi Kitazawa': 0.01509433962264151,
 'DZ-BT03/EX33EN : RAISE A SUILEN, MASKING': 0.01509433962264151,
 'DZ-SS09/016EN : Electrake Dracokid': 0.01509433962264151,
 'DZ-BT03/EX15EN-S : Pastel✽Palettes, Eve Wakamiya': 0.01509433962264151,
 'DZ-BT09/SR03EN : Battle Monk of Water Scales, Ryuutou': 0.01509433962264151,
 'D-BT13/020EN : Great Scale Supporter, Rovania': 0.01509433962264151,
 'DZ-BT06/024EN : Stealth Fiend, Futakuchiyo': 0.01509433962264151,
 'D-PR/353EN : Guardian Monk of Raging Flames, Monju': 0.01509433962264151,
 'D-BT11/EX31EN : RAISE A SUILEN, LAYER': 0.013207547169811321,
 'DZ-BT03/EX39EN : MyGO!!!!! Soyo Nagasaki': 0.013207547169811321,
 'DZ-BT03/EX40EN : MyGO!!!!! Taki Shiina': 0.013207547169811321,
 "DZ-BT03/EX03EN : Poppin'Party, Rimi Ushigome": 0.013207547169811321,
 'DZ-BT03/EX16EN : Roselia, Yukina Minato': 0.013207547169811321,
 'DZ-BT03/EX25EN : Hello, Happy World! Michelle': 0.013207547169811321,
 "DZ-SS05/CR30EN : 'Usotsuki! Gokuoh-kun' Gokuoh": 0.013207547169811321,
 'DZ-BT12/SR03EN : Dragonvortex, Belligeacro': 0.013207547169811321,
 'DZ-BT02/077EN : Stardust Blade': 0.013207547169811321,
 'DZ-BT03/EX22EN-S : Hello, Happy World! Kaoru Seta': 0.013207547169811321,
 'DZ-BT03/EX32EN : RAISE A SUILEN, LOCK': 0.013207547169811321,
 'DZ-SS09/008EN : Inductance Dragon': 0.013207547169811321,
 'DZ-BT03/EX19EN : Roselia, Ako Udagawa': 0.011320754716981131,
 'DZ-BT03/EX18EN-S : Roselia, Lisa Imai': 0.011320754716981131,
 'DZ-BT03/EX36EN : MyGO!!!!! Tomori Takamatsu': 0.011320754716981131,
 'D-BT02/067EN : Flame Dragon Bombardment': 0.011320754716981131,
 'D-BT11/EX09EN-S : Afterglow, Tomoe Udagawa': 0.011320754716981131,
 'DZ-BT03/EX40EN-S : MyGO!!!!! Taki Shiina': 0.011320754716981131,
 'D-BT11/003EN : Dragritter, Lateefa': 0.011320754716981131,
 "DZ-BT03/EX05EN : Poppin'Party, Arisa Ichigaya": 0.011320754716981131,
 'DZ-BT03/EX20EN : Roselia, Rinko Shirokane': 0.011320754716981131,
 'DZ-BT03/EX09EN : Afterglow, Tomoe Udagawa': 0.011320754716981131,
 'DZ-BT03/EX25EN-S : Hello, Happy World! Michelle': 0.011320754716981131,
 'DZ-BT03/EX07EN-S : Afterglow, Moca Aoba': 0.011320754716981131,
 'DZ-BT03/EX34EN : RAISE A SUILEN, PAREO': 0.011320754716981131,
 'DZ-BT03/EX35EN : RAISE A SUILEN, CHU²': 0.011320754716981131,
 'D-BT11/EX06EN : Afterglow, Ran Mitake': 0.011320754716981131,
 'D-BT11/EX33EN : RAISE A SUILEN, MASKING': 0.009433962264150943,
 'DZ-BT03/EX08EN : Afterglow, Himari Uehara': 0.009433962264150943,
 'DZ-BT03/EX20EN-S : Roselia, Rinko Shirokane': 0.009433962264150943,
 'DZ-BT03/EX36EN-S : MyGO!!!!! Tomori Takamatsu': 0.009433962264150943,
 'DZ-BT03/EX06EN : Afterglow, Ran Mitake': 0.009433962264150943,
 "D-PR/748EN : The Ancient Magus' Bride": 0.009433962264150943,
 'DZ-BT03/EX29EN : Morfonica, Tsukushi Futaba': 0.009433962264150943,
 "D-BT11/EX04EN : Poppin'Party, Saya Yamabuki": 0.009433962264150943,
 'D-BT11/EX23EN : Hello, Happy World! Hagumi Kitazawa': 0.009433962264150943,
 'DZ-BT03/EX26EN-S : Morfonica, Mashiro Kurata': 0.009433962264150943,
 'D-BT11/EX15EN-S : Pastel✽Palettes, Eve Wakamiya': 0.009433962264150943,
 'D-BT11/EX25EN-S : Hello, Happy World! Michelle': 0.009433962264150943,
 'DZ-BT03/EX38EN-S : MyGO!!!!! Rana Kaname': 0.009433962264150943,
 'D-BT11/EX07EN : Afterglow, Moca Aoba': 0.009433962264150943,
 'D-BT11/EX31EN-S : RAISE A SUILEN, LAYER': 0.009433962264150943,
 'D-SS08/023EN : Elementaria Sanctitude': 0.009433962264150943,
 'DZ-BT03/EX11EN-S : Pastel✽Palettes, Aya Maruyama': 0.009433962264150943,
 'DZ-BT03/EX33EN-S : RAISE A SUILEN, MASKING': 0.009433962264150943,
 'DZ-BT03/EX07EN : Afterglow, Moca Aoba': 0.009433962264150943,
 'DZ-BT03/EX21EN-S : Hello, Happy World! Kokoro Tsurumaki': 0.009433962264150943,
 'D-BT07/058EN : Dragritter, Midhat': 0.009433962264150943,
 'DZ-BT03/EX24EN : Hello, Happy World! Kanon Matsubara': 0.009433962264150943,
 'D-BT11/EX10EN : Afterglow, Tsugumi Hazawa': 0.007547169811320755,
 'D-BT11/EX13EN : Pastel✽Palettes, Chisato Shirasagi': 0.007547169811320755,
 'DZ-BT03/EX17EN : Roselia, Sayo Hikawa': 0.007547169811320755,
 'D-PR/578EN : Elementaria Sanctitude': 0.007547169811320755,
 'D-BT11/EX28EN-S : Morfonica, Nanami Hiromachi': 0.007547169811320755,
 "DZ-SS05/GCR02EN : 'Butto Bird' Suzume": 0.007547169811320755,
 'D-BT11/EX26EN : Morfonica, Mashiro Kurata': 0.007547169811320755,
 'D-BT11/EX17EN : Roselia, Sayo Hikawa': 0.007547169811320755,
 'DZ-BT03/EX22EN : Hello, Happy World! Kaoru Seta': 0.007547169811320755,
 'DZ-BT03/EX14EN-S : Pastel✽Palettes, Maya Yamato': 0.007547169811320755,
 'D-BT11/EX13EN-S : Pastel✽Palettes, Chisato Shirasagi': 0.007547169811320755,
 'DZ-BT03/EX29EN-S : Morfonica, Tsukushi Futaba': 0.007547169811320755,
 'D-BT11/EX07EN-S : Afterglow, Moca Aoba': 0.007547169811320755,
 'D-BT11/EX17EN-S : Roselia, Sayo Hikawa': 0.007547169811320755,
 'DZ-BT03/EX37EN-S : MyGO!!!!! Anon Chihaya': 0.007547169811320755,
 'DZ-BT03/EX08EN-S : Afterglow, Himari Uehara': 0.007547169811320755,
 'DZ-BT03/EX10EN-S : Afterglow, Tsugumi Hazawa': 0.007547169811320755,
 'D-BT11/EX06EN-S : Afterglow, Ran Mitake': 0.007547169811320755,
 'D-PR/803EN-S : Having Fun at Round1, Nao Inabe': 0.007547169811320755,
 "D-BT11/EX04EN-S : Poppin'Party, Saya Yamabuki": 0.007547169811320755,
 'DZ-BT03/EX27EN : Morfonica, Toko Kirigaya': 0.005660377358490566,
 'DZ-BT03/EX19EN-S : Roselia, Ako Udagawa': 0.005660377358490566,
 'D-SS05/004EN : Evergreen Transphere': 0.005660377358490566,
 'D-PR/501EN : will+Dress Season2, Yu-yu Kondo': 0.005660377358490566,
 'D-SS02/SP11EN : Cure Flare Dracokid': 0.005660377358490566,
 'DZ-BT03/EX10EN : Afterglow, Tsugumi Hazawa': 0.005660377358490566,
 'D-BT11/EX19EN : Roselia, Ako Udagawa': 0.005660377358490566,
 'D-BT11/EX12EN : Pastel✽Palettes, Hina Hikawa': 0.005660377358490566,
 'D-BT11/EX14EN : Pastel✽Palettes, Maya Yamato': 0.005660377358490566,
 'D-BT11/EX20EN : Roselia, Rinko Shirokane': 0.005660377358490566,
 'D-BT11/EX32EN : RAISE A SUILEN, LOCK': 0.005660377358490566,
 'DZ-BT03/EX39EN-S : MyGO!!!!! Soyo Nagasaki': 0.005660377358490566,
 'DZ-BT03/EX28EN-S : Morfonica, Nanami Hiromachi': 0.005660377358490566,
 "D-BT11/EX01EN-S : Poppin'Party, Kasumi Toyama": 0.005660377358490566,
 'D-BT11/EX10EN-S : Afterglow, Tsugumi Hazawa': 0.005660377358490566,
 'D-BT11/EX26EN-S : Morfonica, Mashiro Kurata': 0.005660377358490566,
 'D-BT11/EX18EN-S : Roselia, Lisa Imai': 0.005660377358490566,
 'D-BT11/EX19EN-S : Roselia, Ako Udagawa': 0.005660377358490566,
 "DZ-BT03/EX02EN-S : Poppin'Party, Tae Hanazono": 0.005660377358490566,
 'DZ-BT03/EX09EN-S : Afterglow, Tomoe Udagawa': 0.005660377358490566,
 'D-BT09/019EN : Desolate Spark Dragon': 0.005660377358490566,
 'D-BT11/EX25EN : Hello, Happy World! Michelle': 0.005660377358490566,
 "DZ-BT03/EX03EN-S : Poppin'Party, Rimi Ushigome": 0.005660377358490566,
 "DZ-BT03/EX04EN-S : Poppin'Party, Saya Yamabuki": 0.005660377358490566,
 "DZ-BT03/EX05EN-S : Poppin'Party, Arisa Ichigaya": 0.005660377358490566,
 'D-BT08/034EN : Frying Shot Dragon, Crumstego': 0.005660377358490566,

In [ ]:
diff_dict = defaultdict(int)
for k, v in bot_dict.items():
    try:
        diff_dict[k] = top_dict[k] - v
    except:
        continue

diff_dict = {k:v for k,v in sorted(diff_dict.items(), key=lambda k: k[1], reverse=True)}

In [ ]:
diff_dict

{'DZ-SS01/Re05EN : Stealth Fiend, Amaviera': 0.2850284495021338,
 'D-SS09/008EN-R : Stealth Dragon, Utsuroi': 0.248221906116643,
 'D-SS01/008EN : Blaze Maiden, Zonne': 0.21752015173067807,
 'D-PR/413EN : New Horizons, Yumenokessho POPY': 0.20738501659554293,
 'D-SS05/Re06EN : Flare Veil Dragon': 0.2029990516832622,
 'D-SS09/008EN : Stealth Dragon, Utsuroi': 0.18326220957799907,
 'D-SS05/Re04EN : Blaze Maiden, Parama': 0.15801327643432905,
 'DZ-SS01/Re37EN : Stealth Fiend, Shenryi': 0.1554646752015173,
 'DZ-SS04/017EN-R : Stardust Blade': 0.15416073968705546,
 'DZ-SS05/098EN : Nusa~~': 0.1540422000948317,
 'DZ-BT08/SR03EN : Dragritter, Nirmihn': 0.15238264580369848,
 "DZ-SS08/FFR01EN : Vyrgilla, 'Rewrite Form: Alfknights'": 0.1477596017069701,
 'D-SS09/016EN : Stealth Dragon, Shikintan': 0.1420104314841157,
 'DZ-SS05/037EN : Are You Trying To Kill Me~~~~!!!!': 0.13981744902797535,
 'D-SS09/013EN : Stealth Dragon, Madowazu': 0.13537221431958274,
 'DZ-SS01/028EN : Rogue Beast, Sunegosuri': 0.12701517306780466,
 'BCS2526/VGS01 : Guardian Monk of Raging Flames, Monju': 0.12227358937885255,
 'D-PR/445EN : Stealth Dragon, Shikintan': 0.11136794689426269,
 'D-BT03/SP36EN : Burning Flail Dragon': 0.11024182076813657,
 'DZ-SS04/006EN-R : Ezerwur': 0.10170697012802277,
 'D-BT11/065EN : Defensing Roar': 0.09998814604077766,
 'DZ-BT03/EX11EN : Pastel✽Palettes, Aya Maruyama': 0.09933617828354671,
 'DZ-SS05/034EN : Cold Noodles Are Gone': 0.09269796111901377,
 'D-SS05/Re05EN : Burning Flail Dragon': 0.09121621621621623,
 'DZ-BT08/003EN : Dragritter, Nirmihn': 0.0911569464201043,
 'DZ-SS08/001EN : Dragritter, Miqdard': 0.0875414888572783,
 'DZ-SS09/010EN : Stealth Fiend, Shenryi': 0.08380749170222845,
 'D-PR/414EN : New Horizons, Yumenokessho ROSE': 0.08250355618776672,
 'D-BT07/Re06EN : Burning Flail Dragon': 0.08214793741109531,
 "DZ-SS05/CR02EN : 'Butto Bird' Suzume": 0.08102181128496919,
 'D-BT05/022EN : Stealth Fiend, Amaviera': 0.07942152678994785,
 'D-SS12/SIR18EN : Blaze Maiden, Parama': 0.0769914651493599,
 'D-SS12/092EN : Flare Veil Dragon': 0.07479848269321955,
 'D-SS12/093EN : Blaze Maiden, Parama': 0.07177572309151256,
 'DZ-BT01/SR03EN : Dragritter, Falhart': 0.06679706021811285,
 'D-PR/803EN : Having Fun at Round1, Nao Inabe': 0.060514461830251304,
 'DZ-SS04/001EN : Rewrite the Star, Vyrgilla': 0.05891417733522997,
 'DZ-BT07/152EN : Light Elemental, Pachiri': 0.058321479374110974,
 'D-PR/289EN : Yumenokessho ROSE': 0.05796586059743955,
 'DZ-SS05/033EN : Who Are These Guys...?': 0.055832147937411106,
 "D-PR/748EN : The Ancient Magus' Bride": 0.051861071597913706,
 'D-PR/442EN : Stealth Dragon, Madowazu': 0.050734945471787585,
 'DZ-BT07/055EN : Burning Flail Dragon': 0.05026078710289239,
 'DZ-SS09/001EN : Rewrite the Star, Vyrgilla': 0.05002370791844468,
 'D-BT01/SP13EN : Dragon Deity King of Resurgence, Dragveda': 0.04919393077287815,
 'DZ-SS04/001EN-R : Rewrite the Star, Vyrgilla': 0.0482456140350877,
 'D-PR/WO01EN : Stealth Fiend, Souko': 0.04551920341394028,
 'DZ-SS10/020EN : Protection: Twincast': 0.04480796586059746,
 'D-BT02/030EN : Blaze Maiden, Parama': 0.0394144144144144,
 'DZ-BT03/043EN : Protection: Twincast': 0.03876244665718348,
 'D-BT11/EX10EN : Afterglow, Tsugumi Hazawa': 0.03834755808440019,
 'DZ-BT01/FFR03EN : Dragritter, Falhart': 0.03722143195827407,
 'DZ-BT01/003EN : Dragritter, Falhart': 0.036925082977714574,
 'DZ-BT05/003EN : Summit Flare Dragon': 0.03621384542437178,
 'D-PR/726EN : Variance Ray Dragon': 0.03597676623992413,
 'DZ-SS09/009EN-R : Opening of the End, Enwing': 0.034909909909909914,
 'D-SS12/SIR19EN : Burning Flail Dragon': 0.0339023233760076,
 'DZ-SS09/019EN : Blazing Star Cross': 0.03200568990042674,
 'DZ-BT03/EX16EN : Roselia, Yukina Minato': 0.03176861071597914,
 'D-SS12/SIR20EN : Flare Veil Dragon': 0.03099810336652442,
 'D-PR/090EN : Burning Flail Dragon ': 0.0299312470365102,
 'DZ-BT01/143EN : Light Elemental, Pachiri': 0.028449502133712667,
 'DZ-BT01/054EN : Guardian Monk of Raging Flames, Monju': 0.028271692745376997,
 'DZ-SS10/021EN : Shiki Otei': 0.028093883357041258,
 'D-BT07/Re01EN : Blaze Maiden, Parama': 0.02696775723091513,
 'D-PR/730EN : Stealth Dragon, Utsuroi': 0.025189663347558088,
 'D-BT11/EX12EN : Pastel✽Palettes, Hina Hikawa': 0.024834044570886678,
 'D-BT11/EX14EN : Pastel✽Palettes, Maya Yamato': 0.024834044570886678,
 'D-BT11/EX20EN : Roselia, Rinko Shirokane': 0.024834044570886678,
 'D-BT11/EX32EN : RAISE A SUILEN, LOCK': 0.024834044570886678,
 'D-BT06/016EN : Dragon Deity King of Resurgence, Dragveda': 0.024774774774774785,
 'DZ-SS09/013EN : Dragon Deity King of Resurgence, Dragveda': 0.024715504978662872,
 'D-BT11/EX13EN : Pastel✽Palettes, Chisato Shirasagi': 0.022641062114746327,
 'D-BT11/EX17EN : Roselia, Sayo Hikawa': 0.022641062114746327,
 'D-BT07/Re11EN : Flare Veil Dragon': 0.022581792318634428,
 'D-SS01/SP06EN : Blaze Maiden, Rona': 0.021514935988620205,
 "D-PR/747EN : The Ancient Magus' Bride": 0.021100047415836903,
 'D-BT11/EX23EN : Hello, Happy World! Hagumi Kitazawa': 0.020448079658605976,
 'DZ-BT05/SR03EN : Summit Flare Dragon': 0.018551446183025136,
 'D-SS01/SP05EN : Blaze Maiden, Zonne': 0.018551446183025136,
 'DZ-BT01/019EN : Dragon Deity King of Resurgence, Dragveda': 0.018195827406353726,
 'D-BT04/SP31EN : Flare Veil Dragon': 0.017840208629682316,
 'D-BT12/003EN : Red Jeweled Beast, Galnet': 0.016417733522996684,
 'DZ-BT03/EX40EN : MyGO!!!!! Taki Shiina': 0.016062114746325275,
 'DZ-BT12/SR03EN : Dragonvortex, Belligeacro': 0.016062114746325275,
 'D-BT01/066EN : White Light Dragon, Parasolace': 0.014580369843527743,
 'DZ-BT03/EX38EN : MyGO!!!!! Rana Kaname': 0.013869132290184924,
 'D-BT11/EX11EN : Pastel✽Palettes, Aya Maruyama': 0.013869132290184924,
 'DZ-SS01/031EN : Refreshing Wind Dragon, Dinobreeze': 0.012387387387387393,
 'D-SS02/015EN : Cure Flare Dracokid': 0.012387387387387393,
 'DZ-PS02/017EN : Elementaria Sanctitude': 0.011676149834044573,
 'DZ-PS01/017EN : Elementaria Sanctitude': 0.011676149834044573,
 'DZ-BT03/EX32EN-S : RAISE A SUILEN, LOCK': 0.011320531057373164,
 'DZ-BT03/EX12EN : Pastel✽Palettes, Hina Hikawa': 0.011320531057373164,
 'DZ-BT03/EX14EN : Pastel✽Palettes, Maya Yamato': 0.011320531057373164,
 'DZ-BT03/EX16EN-S : Roselia, Yukina Minato': 0.011320531057373164,
 'DZ-BT03/EX17EN-S : Roselia, Sayo Hikawa': 0.011320531057373164,
 'DZ-BT03/EX15EN : Pastel✽Palettes, Eve Wakamiya': 0.011320531057373164,
 'D-BT11/EX27EN-S : Morfonica, Toko Kirigaya': 0.011320531057373164,
 "D-BT11/EX02EN-S : Poppin'Party, Tae Hanazono": 0.011320531057373164,
 'D-BT11/EX35EN : RAISE A SUILEN, CHU²': 0.011320531057373164,
 'D-BT11/EX34EN : RAISE A SUILEN, PAREO': 0.011320531057373164,
 'D-BT11/EX29EN-S : Morfonica, Tsukushi Futaba': 0.011320531057373164,
 'DZ-BT12/EX45EN : 10th anniv Ave Mujica, Oblivionis': 0.011320531057373164,
 'DZ-BT03/EX39EN-S : MyGO!!!!! Soyo Nagasaki': 0.009127548601232813,
 'D-SS05/004EN : Evergreen Transphere': 0.009127548601232813,
 'DZ-BT03/EX28EN-S : Morfonica, Nanami Hiromachi': 0.009127548601232813,
 'D-SS02/SP11EN : Cure Flare Dracokid': 0.009127548601232813,
 'D-PR/501EN : will+Dress Season2, Yu-yu Kondo': 0.009127548601232813,
 'DZ-BT03/EX19EN-S : Roselia, Ako Udagawa': 0.009127548601232813,
 'DZ-BT03/EX10EN : Afterglow, Tsugumi Hazawa': 0.009127548601232813,
 'D-BT11/EX19EN : Roselia, Ako Udagawa': 0.009127548601232813,
 'DZ-BT03/EX27EN : Morfonica, Toko Kirigaya': 0.009127548601232813,
 'D-PR/382EN : Wood Elemental, Leafy': 0.008357041251778101,
 'DZ-SS09/020EN : Union the Sky': 0.007942152678994785,
 'DZ-BT03/EX29EN-S : Morfonica, Tsukushi Futaba': 0.006934566145092462,
 'DZ-BT03/EX17EN : Roselia, Sayo Hikawa': 0.006934566145092462,
 'D-PR/578EN : Elementaria Sanctitude': 0.006934566145092462,
 'D-BT11/EX28EN-S : Morfonica, Nanami Hiromachi': 0.006934566145092462,
 "DZ-SS05/GCR02EN : 'Butto Bird' Suzume": 0.006934566145092462,
 'DZ-BT03/EX14EN-S : Pastel✽Palettes, Maya Yamato': 0.006934566145092462,
 'D-BT11/EX13EN-S : Pastel✽Palettes, Chisato Shirasagi': 0.006934566145092462,
 'DZ-BT03/EX22EN : Hello, Happy World! Kaoru Seta': 0.006934566145092462,
 'DZ-SS09/011EN-R : Flare Cosmor': 0.006697486960644872,
 'D-BT05/SP19EN : Stealth Fiend, Amaviera': 0.00616405879563775,
 'D-BT04/034EN : Flare Veil Dragon': 0.00551209103840683,
 'D-PR/124EN : Elementaria Sanctitude': 0.005393551446183031,
 'D-BT11/EX20EN-S : Roselia, Rinko Shirokane': 0.005097202465623521,
 'D-BT11/EX33EN : RAISE A SUILEN, MASKING': 0.004741583688952111,
 'DZ-BT03/EX36EN-S : MyGO!!!!! Tomori Takamatsu': 0.004741583688952111,
 'DZ-BT03/EX38EN-S : MyGO!!!!! Rana Kaname': 0.004741583688952111,
 'DZ-BT03/EX08EN : Afterglow, Himari Uehara': 0.004741583688952111,
 "D-BT11/EX04EN : Poppin'Party, Saya Yamabuki": 0.004741583688952111,
 'DZ-BT03/EX06EN : Afterglow, Ran Mitake': 0.004741583688952111,
 'DZ-BT03/EX26EN-S : Morfonica, Mashiro Kurata': 0.004741583688952111,
 'DZ-BT03/EX29EN : Morfonica, Tsukushi Futaba': 0.004741583688952111,
 'DZ-BT03/EX20EN-S : Roselia, Rinko Shirokane': 0.004741583688952111,
 'D-BT11/EX15EN-S : Pastel✽Palettes, Eve Wakamiya': 0.004741583688952111,
 'D-BT11/EX25EN-S : Hello, Happy World! Michelle': 0.004741583688952111,
 'D-BT03/030EN : Burning Flail Dragon': 0.004445234708392587,
 'DZ-SS09/020EN-R : Union the Sky': 0.0039710763394973925,
 'D-PR/741EN : Yumenokessho PASTEL': 0.0036154575628259897,
 'D-SS09/012EN : Dragon Deity King of Resurgence, Dragveda': 0.00325983878615458,
 'DZ-BT03/EX36EN : MyGO!!!!! Tomori Takamatsu': 0.0025486012328117605,
 'DZ-BT03/EX19EN : Roselia, Ako Udagawa': 0.0025486012328117605,
 'DZ-BT03/EX18EN-S : Roselia, Lisa Imai': 0.0025486012328117605,
 'D-PR/802EN : Having Fun at Round1, Akina Myodo': 0.001422475106685639,
 'DZ-SS09/007EN : Ezerwur': 0.0011853959222378752,
 'D-BT07/002EN : Meteor Flare Dragon': 0.0007112375533428195,
 'D-BT11/EX31EN : RAISE A SUILEN, LAYER': 0.00035561877667140973,
 "DZ-BT03/EX03EN : Poppin'Party, Rimi Ushigome": 0.00035561877667140973,
 'DZ-BT03/EX39EN : MyGO!!!!! Soyo Nagasaki': 0.00035561877667140973,
 "DZ-SS05/CR30EN : 'Usotsuki! Gokuoh-kun' Gokuoh": 0.00035561877667140973,
 'DZ-BT03/EX25EN : Hello, Happy World! Michelle': 0.00035561877667140973,
 'D-PR/288EN : Yumenokessho POPY': -0.0007705073494547118,
 'DZ-SS04/005EN-R : Flag-raising of Courage, Fanvare': -0.0012446657183499132,
 'DZ-BT01/FR08EN : Guardian Monk of Raging Flames, Monju': -0.0016002844950213369,
 'DZ-BT03/EX33EN : RAISE A SUILEN, MASKING': -0.001837363679468941,
 'DZ-BT03/EX23EN : Hello, Happy World! Hagumi Kitazawa': -0.001837363679468941,
 'DZ-SS09/006EN : Flag-raising of Courage, Fanvare': -0.001955903271692816,
 'DZ-SS04/005EN : Flag-raising of Courage, Fanvare': -0.0024300616405878994,
 'D-PR/229EN : Elementaria Sanctitude': -0.002607871028923653,
 'D-PR/794EN : Bellringer Angel': -0.002607871028923653,
 'D-PR/356EN : Flare Veil Dragon': -0.003674727358937882,
 'DZ-BT03/EX37EN : MyGO!!!!! Anon Chihaya': -0.004030346135609292,
 'D-BT11/EX34EN-S : RAISE A SUILEN, PAREO': -0.004030346135609292,
 'DZ-SS09/018EN : Stardust Blade': -0.004919393077287809,
 'D-PR/466EN : Divinez, Nao Inabe': -0.0062233285917496425,
 'DZ-SS09/013EN-R : Dragon Deity King of Resurgence, Dragveda': -0.0070531057373162676,
 'D-BT01/031EN : Twin Buckler Dragon': -0.007823613086770959,
 'D-SS01/011EN : Blaze Maiden, Rona': -0.008119962067330483,
 'DZ-BT05/FFR03EN : Summit Flare Dragon': -0.010253674727358934,
 'D-BT11/EX16EN-S : Roselia, Yukina Minato': -0.010609293504030344,
 'DZ-BT06/020EN : Fire Regalis': -0.010609293504030344,
 'DZ-SS06/020EN : Elementaria Sanctitude': -0.012091038406827875,
 'D-PR/729EN : Stealth Dragon, Utsuroi': -0.012091038406827875,
 'D-PR/824EN : Rogue Beast, Sunegosuri': -0.012802275960170695,
 'DZ-BT02/043EN : Rewrite the Star, Vyrgilla': -0.013217164532954004,
 'D-PR/576EN : Flare Veil Dragon': -0.014639639639639636,
 'DZ-BT12/003EN : Dragonvortex, Belligeacro': -0.014698909435751528,
 'D-PR/352EN : Elementaria Sanctitude': -0.019025604551920337,
 'DZ-SS01/015EN : Flame Leaf Chaotic Dance, Hakusui&amp;Remred': -0.019025604551920337,
 'D-PR/503EN : overDress, Yu-yu Kondo': -0.019381223328591747,
 'D-BT01/H10EN : White Light Dragon, Parasolace': -0.02050734945471787,
 'DZ-SS09/017EN-R : Refreshing Wind Dragon, Dinobreeze': -0.022344713134186817,
 'D-PR/577EN : Blaze Maiden, Parama': -0.022344713134186817,
 'D-PR/795EN : Lyrial, Archer Throne': -0.022700331910858226,
 'D-PR/559EN : Defensing Roar': -0.024596965386439074,
 'DZ-BT03/046EN : Blaze Maiden, Parama': -0.0247747747747748,
 'D-PR/002EN : Twin Buckler Dragon': -0.0260194404931247,
 'D-SD06/010EN : Conduct Spark Dragon': -0.026730678046467518,
 'DZ-SS01/Re04EN : Cure Flare Dracokid': -0.02815315315315315,
 'D-BT01/063EN : Conduct Spark Dragon': -0.028212422949265042,
 'D-SD01/014EN : Blaze Maiden, Rona': -0.028627311522048365,
 'D-PR/725EN : Variance Ray Dragon': -0.028864390706495935,
 'DZ-SS10/020EN-R : Protection: Twincast': -0.02999051683262209,
 'DZ-SS04/006EN : Ezerwur': -0.030583214793741043,
 'D-PR/354EN : Blaze Maiden, Parama': -0.03253911806543385,
 'DZ-BT02/FR05EN : Rewrite the Star, Vyrgilla': -0.03307254623044098,
 'DZ-BT09/003EN : Battle Monk of Water Scales, Ryuutou': -0.03402086296823138,
 'DZ-SS09/006EN-R : Flag-raising of Courage, Fanvare': -0.03461356092935036,
 'D-BT02/SP26EN : Blaze Maiden, Parama': -0.03514698909435751,
 'DZ-BT07/020EN : Dragon Deity King of Resurgence, Dragveda': -0.0391773352299668,
 'DZ-SS09/014EN-R : Rogue Beast, Sunegosuri': -0.04065908013276434,
 'DZ-BT03/044EN : Burning Flail Dragon': -0.0425557136083452,
 'D-PR/558EN : Defensing Roar': -0.0428520625889047,
 'DZ-SS09/019EN-R : Blazing Star Cross': -0.04516358463726888,
 'D-PR/333EN : Stealth Fiend, Shenryi': -0.04800853485064005,
 'D-BT01/SP26EN : Twin Buckler Dragon': -0.05085348506401137,
 'D-PR/516EN : Union the Sky': -0.05085348506401137,
 'D-BT01/H03EN : Twin Buckler Dragon': -0.05595068752963489,
 'D-BT06/038EN : Sparkle Rejector Dragon': -0.05891417733522997,
 'DZ-SS04/017EN : Stardust Blade': -0.05926979611190136,
 'D-BT02/H05EN : Blaze Maiden, Parama': -0.061107159791370325,
 "DZ-SS08/007EN : Vyrgilla, 'Rewrite Form: Alfknights'": -0.06223328591749633,
 'D-BT01/013EN : Dragon Deity King of Resurgence, Dragveda': -0.06294452347083926,
 'D-BT06/FR06EN : Sparkle Rejector Dragon': -0.0647226173541963,
 'D-PR/742EN : Yumenokessho HALO': -0.06762683736367947,
 'DZ-SS09/007EN-R : Ezerwur': -0.067923186344239,
 'DZ-BT08/FFR03EN : Dragritter, Nirmihn': -0.07059032716927455,
 'DZ-SS08/032EN : Blaze War Monk, Sougyou': -0.07254623044096725,
 'D-SS05/033EN : Stealth Dragon, Madowazu': -0.0819108582266477,
 'D-BT01/H07EN : Conduct Spark Dragon': -0.0822664770033191,
 'DZ-SS09/001EN-R : Rewrite the Star, Vyrgilla': -0.08819345661450917,
 'DZ-BT07/070EN : Guardian Monk of Raging Flames, Monju': -0.0908013276434329,
 'DZ-BT07/056EN : Flare Veil Dragon': -0.09186818397344712,
 'DZ-SS09/010EN-R : Stealth Fiend, Shenryi': -0.0951280227596017,
 'D-SS05/Re03EN : Twin Buckler Dragon': -0.09945471787577051,
 'DZ-BT03/045EN : Flare Veil Dragon': -0.10858226647700331,
 'D-BT06/065EN : Blaze War Monk, Sougyou': -0.11444997629208156,
 'DZ-SS09/011EN : Flare Cosmor': -0.1468112849691796,
 'DZ-SS09/018EN-R : Stardust Blade': -0.1503082029397819,
 'DZ-SS09/017EN : Refreshing Wind Dragon, Dinobreeze': -0.17407539118065435,
 'DZ-SS04/016EN : Refreshing Wind Dragon, Dinobreeze': -0.18106922712185872,
 'DZ-SS08/035EN : Blaze Maiden, Reony': -0.18314366998577525,
 'DZ-SS09/009EN : Opening of the End, Enwing': -0.18486249407302036,
 'DZ-SS09/021EN : Zero Tendo': -0.23613086770981506,
 'DZ-SS09/014EN : Rogue Beast, Sunegosuri': -0.2576458036984352,
 'D-SD01/011EN : Blaze Maiden, Zonne': -0.25811996206733046,
 'DZ-SS04/011EN : Twin Buckler Dragon': -0.25930535798956855,
 'DZ-SS04/013EN : Rogue Beast, Sunegosuri': -0.30286865813181596}

This is a good start, but the vanity cards really muddy the waters, so we need to clear things up.